In [86]:
import pandas as pd
import numpy as np

In [87]:
table5 = "NTH Soil data 2005 table count 5-8.xlsx"

In [88]:
#run this across each sheet of the file
table_df = pd.read_excel(table5, sheet_name = 2)

In [99]:
table_df = table_df.replace('─',np.nan)
table_df

,Sample ID,TP-41,TP-41,TP-41,TP-42,TP-42,TP-42,TP-42.1,TP-42.1,TP-42.1,...,TP-52,TP-53,TP-53,TP-53,TP-54,TP-54,TP-54,TP-55,TP-55,TP-55
0,Sample Depth (ft bgs),1-3,1-3,1-3,0-2,0-2,0-2,2-4,2-4,2-4,...,6-11.5,2.5-13,2.5-13,2.5-13,3-12,3-12,3-12,0-3,0-3,0-3
1,Collection Date,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,...,2005-09-24 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-23 00:00:00,2005-09-23 00:00:00,2005-09-23 00:00:00,2005-09-24 00:00:00,2005-09-24 00:00:00,2005-09-24 00:00:00
2,VOC Analysis Date,2005-10-06 00:00:00,2005-10-06 00:00:00,2005-10-06 00:00:00,NT,NT,NT,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,...,2005-10-01 00:00:00,2005-10-06 00:00:00,2005-10-06 00:00:00,2005-10-06 00:00:00,2005-10-01 00:00:00,2005-10-01 00:00:00,2005-10-01 00:00:00,2005-10-01 00:00:00,2005-10-01 00:00:00,2005-10-01 00:00:00
3,VOC Analytical Method,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,...,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B
4,VOCs (µg/kg),µg/kg,mg/kg,MDL (ug/kg),µg/kg,mg/kg,MDL (ug/kg),µg/kg,mg/kg,MDL (ug/kg),...,MDL (ug/kg),µg/kg,mg/kg,MDL (ug/kg),µg/kg,mg/kg,MDL (ug/kg),µg/kg,mg/kg,MDL (ug/kg)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,NA = not applicable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NT = not tested,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,PCB = polychlorinated biphenyl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,TP = Test Pit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,ug/kg = microgram per kilograms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
for i in list(range(1,len(table_df.columns),3)):
    
    #rename columns
    newCol1 = str(table_df.columns.tolist()[i])
    newCol2 = str(table_df.columns.tolist()[i])
    table_df.iat[0,i+1]  = table_df.iat[0,i]
    table_df.iat[0,i+2]  = table_df.iat[0,i]
    table_df.iat[1,i+1]  = table_df.iat[1,i]
    table_df.iat[1,i+2]  = table_df.iat[1,i]
    table_df.iat[2,i+1]  = table_df.iat[2,i]
    table_df.iat[2,i+2]  = table_df.iat[2,i]
    table_df.iat[3,i+1]  = table_df.iat[3,i]
    table_df.iat[3,i+2]  = table_df.iat[3,i]
    table_df = table_df.rename(columns = {table_df.columns.to_list()[i+1]:newCol1})
    table_df = table_df.rename(columns = {table_df.columns.to_list()[i+2]:newCol2})
   # print(i)
table_df

,Sample ID,TP-41,TP-41,TP-41,TP-42,TP-42,TP-42,TP-42.1,TP-42.1,TP-42.1,...,TP-52,TP-53,TP-53,TP-53,TP-54,TP-54,TP-54,TP-55,TP-55,TP-55
0,Sample Depth (ft bgs),1-3,1-3,1-3,0-2,0-2,0-2,2-4,2-4,2-4,...,6-11.5,2.5-13,2.5-13,2.5-13,3-12,3-12,3-12,0-3,0-3,0-3
1,Collection Date,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,...,2005-09-24 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-23 00:00:00,2005-09-23 00:00:00,2005-09-23 00:00:00,2005-09-24 00:00:00,2005-09-24 00:00:00,2005-09-24 00:00:00
2,VOC Analysis Date,2005-10-06 00:00:00,2005-10-06 00:00:00,2005-10-06 00:00:00,NT,NT,NT,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,...,2005-10-01 00:00:00,2005-10-06 00:00:00,2005-10-06 00:00:00,2005-10-06 00:00:00,2005-10-01 00:00:00,2005-10-01 00:00:00,2005-10-01 00:00:00,2005-10-01 00:00:00,2005-10-01 00:00:00,2005-10-01 00:00:00
3,VOC Analytical Method,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,...,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B,SW846 8260B
4,VOCs (µg/kg),µg/kg,mg/kg,MDL (ug/kg),µg/kg,mg/kg,MDL (ug/kg),µg/kg,mg/kg,MDL (ug/kg),...,MDL (ug/kg),µg/kg,mg/kg,MDL (ug/kg),µg/kg,mg/kg,MDL (ug/kg),µg/kg,mg/kg,MDL (ug/kg)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,NA = not applicable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NT = not tested,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,PCB = polychlorinated biphenyl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,TP = Test Pit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,ug/kg = microgram per kilograms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [101]:
#take the first 23 rows as the voc table
voc_df = table_df.iloc[:23]

##################################################
#transpose it
voc_df = voc_df.transpose()
#make the first row our column titles
voc_df.columns=voc_df.iloc[0]
#drop the duplicate row
voc_df = voc_df.tail(-1)
#drop samples with no detections
voc_df = voc_df.dropna(thresh=6)
##################################################

voc_df.index.name = None

#pull sample id out of index 
voc_df['Sample ID'] = voc_df.index
# shift column to first position
first_column = voc_df.pop('Sample ID')
# insert column using insert(position,column_name,first_column) function
voc_df.insert(0, 'Sample ID', first_column)

###########################################

# #drop VOC details for mergining
voc_df = voc_df.drop('VOC Analysis Date',axis=1)
voc_df = voc_df.drop('VOC Analytical Method',axis=1)
# #voc_df = voc_df.drop('VOCs (µg/kg)',axis=1) - keep for explanation



voc_df
#change format of date to eliminate the time?

Sample ID,Sample ID,Sample Depth (ft bgs),Collection Date,VOCs (µg/kg),Benzene,N-Butylbenzene,Sec-Butylbenzene,Tert-Butylbenzene,Carbon Disulfide,Chlorobenzene,...,Ethylbenzene,Isopropylbenzene,Naphthalene,N-Propylbenzene,Tetrachloroethylene,Toluene,Trichloroethene,"1,2,4-Trimethylbenzene","1,3,5-Trimethylbenzene",Xylene
TP-41,TP-41,1-3,2005-09-27 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-42,TP-42,0-2,2005-09-27 00:00:00,µg/kg,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TP-42.1,TP-42.1,2-4,2005-09-27 00:00:00,µg/kg,NaN,260,94,NaN,NaN,NaN,...,210,NaN,4200,150,NaN,110,NaN,1800,420,1200
TP-42.1,TP-42.1,2-4,2005-09-27 00:00:00,mg/kg,NaN,0.26,0.094,NaN,NaN,NaN,...,0.21,NaN,4.2,0.15,NaN,0.11,NaN,1.8,0.42,1.2
TP-42.1,TP-42.1,2-4,2005-09-27 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-44,TP-44,0-3,2005-09-23 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-46,TP-46,2-5,2005-09-23 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-47,TP-47,7.5-9,2005-09-26 00:00:00,µg/kg,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,540,NaN,NaN,NaN,400,110,NaN,260
TP-47,TP-47,7.5-9,2005-09-26 00:00:00,mg/kg,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.54,NaN,NaN,NaN,0.4,0.11,NaN,0.26
TP-47,TP-47,7.5-9,2005-09-26 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-48,TP-48,3-7,2005-09-26 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-49,TP-49,2-14,2005-09-23 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-51,TP-51,2-10,2005-09-23 00:00:00,µg/kg,NaN,220,130,NaN,NaN,NaN,...,660,NaN,500,150,NaN,160,160,980,100,2500
TP-51,TP-51,2-10,2005-09-23 00:00:00,mg/kg,NaN,0.22,0.13,NaN,NaN,NaN,...,0.66,NaN,0.5,0.15,NaN,0.16,0.16,0.98,0.1,2.5
TP-51,TP-51,2-10,2005-09-23 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-52,TP-52,6-11.5,2005-09-24 00:00:00,µg/kg,NaN,230,180,NaN,NaN,NaN,...,62,NaN,1400,160,NaN,180,NaN,150,NaN,290
TP-52,TP-52,6-11.5,2005-09-24 00:00:00,mg/kg,NaN,0.23,0.18,NaN,NaN,NaN,...,0.062,NaN,1.4,0.16,NaN,0.18,NaN,0.15,NaN,0.29
TP-52,TP-52,6-11.5,2005-09-24 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-53,TP-53,2.5-13,2005-09-27 00:00:00,µg/kg,92,120,120,NaN,NaN,NaN,...,370,NaN,430,160,NaN,130,52,350,NaN,1300
TP-53,TP-53,2.5-13,2005-09-27 00:00:00,mg/kg,0.092,0.12,0.12,NaN,NaN,NaN,...,0.37,NaN,0.43,0.16,NaN,0.13,0.052,0.35,NaN,1.3
TP-53,TP-53,2.5-13,2005-09-27 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-54,TP-54,3-12,2005-09-23 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-55,TP-55,0-3,2005-09-24 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150

In [102]:
#make the BNA table 
BNA_df_1 = table_df.iloc[0:1]
#table 5 is 23:43 but all others are 23:44
BNA_df_2 = table_df.iloc[23:44]
BNA_df = pd.concat([BNA_df_1,BNA_df_2])
#transpose it
BNA_df = BNA_df.transpose()
#make the first row our column titles
BNA_df.columns=BNA_df.iloc[0]
#drop the duplicate row
BNA_df = BNA_df.tail(-1)
#drop BNA details for mergining
BNA_df = BNA_df.drop('BNA Extraction Date',axis=1)
BNA_df = BNA_df.drop('BNA Analysis Date',axis=1)
BNA_df = BNA_df.drop('BNA Analytical Method',axis=1)
#BNA_df = BNA_df.drop('BNAs (µg/kg)',axis=1) - keep for explanation
#drop samples with no detections
BNA_df = BNA_df.dropna(thresh=4)


#pull sample id out of index
BNA_df['Sample ID'] = BNA_df.index

#shift column sample ID to first position
first_column = BNA_df.pop('Sample ID')
#insert column using insert(position,column_name,first_column) function
BNA_df.insert(0, 'Sample ID', first_column)
########################################




BNA_df

Sample ID,Sample ID,Sample Depth (ft bgs),BNAs (µg/kg),Benzo(a)Anthracene,Benzo(b)Fluoranthene,Benzo(a)Pyrene,Benzo(ghl)perylene,Benzo(k)Fluoranthene,Chrysene,2-Cloronaphthalene,"2,4-Dimethylphenol",Di-n-octyl phthalate,Fluoranthene,"Indeno(1,2,3-cd)Pyrene",2-Methylnaphthalene,Bis(2-Ethylhexyl)Phthalate,Phenol,Di-n-butyl phthalate,Phenanthrene,Pyrene
TP-41,TP-41,1-3,MDL (ug/kg),1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TP-42,TP-42,0-2,µg/kg,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TP-42.1,TP-42.1,2-4,µg/kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3800,NaN,NaN,1700,NaN,NaN,4300,3600
TP-42.1,TP-42.1,2-4,mg/kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.8,NaN,NaN,1.7,NaN,NaN,4.3,3.6
TP-42.1,TP-42.1,2-4,MDL (ug/kg),1700,6600,6600,6600,6600,1700,1700,1700,6600,1700,6600,1700,1700,1700,1700,1700,1700
TP-44,TP-44,0-3,MDL (ug/kg),1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TP-46,TP-46,2-5,µg/kg,3100,NaN,NaN,NaN,NaN,3900,NaN,NaN,NaN,3900,NaN,NaN,NaN,NaN,NaN,NaN,6600
TP-46,TP-46,2-5,mg/kg,3.1,NaN,NaN,NaN,NaN,3.9,NaN,NaN,NaN,3.9,NaN,NaN,NaN,NaN,NaN,NaN,6.6
TP-46,TP-46,2-5,MDL (ug/kg),1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TP-47,TP-47,7.5-9,µg/kg,2100,2900,2100,NaN,NaN,2100,NaN,NaN,NaN,4200,NaN,NaN,NaN,NaN,NaN,3300,4400
TP-47,TP-47,7.5-9,mg/kg,2.1,2.9,2.1,NaN,NaN,2.1,NaN,NaN,NaN,4.2,NaN,NaN,NaN,NaN,NaN,3.3,4.4
TP-47,TP-47,7.5-9,MDL (ug/kg),1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TP-48,TP-48,3-7,MDL (ug/kg),330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330
TP-49,TP-49,2-14,µg/kg,NaN,NaN,NaN,NaN,2000,NaN,NaN,NaN,NaN,1900,NaN,NaN,NaN,NaN,NaN,NaN,2100
TP-49,TP-49,2-14,mg/kg,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,1.9,NaN,NaN,NaN,NaN,NaN,NaN,2.1
TP-49,TP-49,2-14,MDL (ug/kg),1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TP-51,TP-51,2-10,µg/kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1700,NaN,NaN,NaN,NaN,NaN,NaN,1700
TP-51,TP-51,2-10,mg/kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.7,NaN,NaN,NaN,NaN,NaN,NaN,1.7
TP-51,TP-51,2-10,MDL (ug/kg),1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TP-52,TP-52,6-11.5,µg/kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1900,NaN,1700,NaN,NaN,NaN,2400,1700
TP-52,TP-52,6-11.5,mg/kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.9,NaN,1.7,NaN,NaN,NaN,2.4,1.7
TP-52,TP-52,6-11.5,MDL (ug/kg),1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TP-53,TP-53,2.5-13,MDL (ug/kg),1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TP-54,TP-54,3-12,MDL (ug/kg),1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TP-55,TP-55,0-3,MDL (ug/kg),1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700

In [103]:
#make the metals table 
metals_df_1 = table_df.iloc[0:1]
#table 5 is 43:59 but all others are 44:60
metals_df_2 = table_df.iloc[44:60]
metals_df = pd.concat([metals_df_1,metals_df_2])
# #transpose it
metals_df = metals_df.transpose()
# #make the first row our column titles
metals_df.columns=metals_df.iloc[0]
# #drop the duplicate row
metals_df = metals_df.tail(-1)
#drop metals details for merging
metals_df = metals_df.drop('Metals Analysis Date',axis=1) 
metals_df = metals_df.drop('Analytical Method',axis=1)
#metals_df = metals_df.drop('Metals (µg/kg)',axis=1) - keep for explanation
#drop samples with no detections
metals_df = metals_df.dropna(thresh=3)

#pull sample id out of index
metals_df['Sample ID'] = metals_df.index
#shift column sample ID to first position
first_column = metals_df.pop('Sample ID')
#insert column using insert(position,column_name,first_column) function
metals_df.insert(0, 'Sample ID', first_column)
############################################



metals_df

Sample ID,Sample ID,Sample Depth (ft bgs),Metals (µg/kg),Arsenic,Barium,Cadmium,Chromium,Chromium IV,"Lead, total (calculated)","Lead, fine fraction","Lead, coarse fraction",Manganese,Mercury,Nickel,Vanadium,Zinc
TP-41,TP-41,1-3,µg/kg,6500,100000,640,930000,4900,65200,99000,64400,18000000,NaN,47000,290000,100000
TP-41,TP-41,1-3,mg/kg,6.5,100,0.64,930,4.9,65.2,99,64.4,18000,NaN,47,290,100
TP-41,TP-41,1-3,MDL (ug/kg),100,1000,50,500,500,1000,1000,1000,1000,50,1000,1000,1000
TP-42,TP-42,0-2,µg/kg,3900,140000,1200,500000,NaN,144000,334000,136000,11000000,150,34000,200000,730000
TP-42,TP-42,0-2,mg/kg,3.9,140,1.2,500,NaN,144,334,136,11000,0.15,34,200,730
TP-42,TP-42,0-2,MDL (ug/kg),100,1000,50,500,500,1000,1000,1000,1000,50,1000,1000,1000
TP-42.1,TP-42.1,2-4,µg/kg,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TP-44,TP-44,0-3,µg/kg,27000,82000,1400,190000,NaN,286000,309000,275000,11000000,90,57000,96000,2200000
TP-44,TP-44,0-3,mg/kg,27,82,1.4,190,NaN,286,309,275,11000,0.09,57,96,2200
TP-44,TP-44,0-3,MDL (ug/kg),100,1000,50,500,500,1000,1000,1000,1000,50,1000,1000,1000
TP-46,TP-46,2-5,µg/kg,7200,200000,1100,130000,NaN,232000,320000,200000,6500000,240,29000,58000,240000
TP-46,TP-46,2-5,mg/kg,7.2,200,1.1,130,NaN,232,320,200,6500,0.24,29,58,240
TP-46,TP-46,2-5,MDL (ug/kg),100,1000,50,500,500,1000,1000,1000,1000,50,1000,1000,1000
TP-47,TP-47,7.5-9,µg/kg,4200,110000,2400,87000,NaN,389000,536000,368000,400000,760,63000,9600,220000
TP-47,TP-47,7.5-9,mg/kg,4.2,110,2.4,87,NaN,389,536,368,400,0.76,63,9.6,220
TP-47,TP-47,7.5-9,MDL (ug/kg),100,1000,50,500,500,1000,1000,1000,1000,50,1000,1000,1000
TP-48,TP-48,3-7,µg/kg,3400,14000,140,5200,NaN,6900,33600,6230,190000,NaN,6300,10000,89000
TP-48,TP-48,3-7,mg/kg,3.4,14,0.14,5.2,NaN,6.9,33.6,6.23,190,NaN,6.3,10,89
TP-48,TP-48,3-7,MDL (ug/kg),100,1000,50,500,500,1000,1000,1000,1000,50,1000,1000,1000
TP-49,TP-49,2-14,µg/kg,8300,160000,1800,470000,NaN,188000,241000,177000,6100000,200,61000,140000,190000
TP-49,TP-49,2-14,mg/kg,8.3,160,1.8,470,NaN,188,241,177,6100,0.2,61,140,190
TP-49,TP-49,2-14,MDL (ug/kg),100,1000,50,500,500,1000,1000,1000,1000,50,1000,1000,1000
TP-51,TP-51,2-10,µg/kg,6200,190000,1900,85000,NaN,232000,305000,215000,900000,420,100000,11000,290000
TP-51,TP-51,2-10,mg/kg,6.2,190,1.9,85,NaN,232,305,215,900,0.42,100,11,290
TP-51,TP-51,2-10,MDL (ug/kg),100,1000,50,500,500,1000,1000,1000,1000,50,1000,1000,1000
TP-52,TP-52,6-11.5,µg/kg,4800,660000,2200,72000,NaN,596000,404000,614000,970000,530,63000,12000,220000
TP-52,TP-52,6-11.5,mg/kg,4.8,660,2.2,72,NaN,596,404,614,NaN,0.53,63,12,220
TP-52,TP-52,6-11.5,MDL (ug/kg),100,1000,50,500,500,1000,1000,1000,1000,50,1000,1000,1000
TP-53,TP-53,2.5-13,µg/kg,5800,190000,1300,42000,NaN,47200,70600,42200,610000,230,49000,9000,150000
TP-53,TP-53,2.5-13,mg/kg,5.8,190,1.3,42,NaN,47.2,70.6,42.2,610,0.23,49,9,150
TP-53,TP-53,2.5-13,MDL (ug/kg),100,1000,50,500,500,1000,1000,1000,1000,50,1000,1000,1000
TP-54,TP-54,3-12,µg/kg,6700,190000,2400,330000,NaN,276000,359000,261000,8200000,510,98000,75000,2000000
TP-54,TP-54,3-12,mg/kg,6.7,190,2.4,330,NaN,276,359,261,8200,0.51,98,75,2000
TP-54,TP-54,3-12,MDL (ug/kg),100,1000,50,500,500,1000,1000,1000,1000,50,1000,1000,1000
TP-55,TP-55,0-3,µg/kg,6600,110000,740,270000,NaN,1270000,1610000,1170000,7200000,100,96000,52000,180000
TP-55,TP-55,0-3,mg/kg,6.6,110,0.74,270,NaN,1270,1610,1170,7200,0.1,96,52,180
TP-55,TP-55,0-3,MDL (ug/kg),100,1000,50,500,500,1000,1000,1000,1000,50,1000,1000,1000

In [104]:
#make the PCBs table 
PCB_df_1 = table_df.iloc[0:1]
#table 5 is 59:65 but all others are 60:66
PCB_df_2 = table_df.iloc[60:66]
PCB_df = pd.concat([PCB_df_1,PCB_df_2])
# #transpose it
PCB_df = PCB_df.transpose()
#make the first row our column titles
PCB_df.columns=PCB_df.iloc[0]
#drop the duplicate row
PCB_df = PCB_df.tail(-1)
#drop samples with no detections
PCB_df = PCB_df.dropna(thresh=3)
#indicate the nondetects
PCB_df = PCB_df.replace(np.nan,'330 U')
#drop PCB details for merging
PCB_df = PCB_df.drop('PCB Extraction Date',axis=1)
PCB_df = PCB_df.drop('PCB Analysis Date',axis=1)
PCB_df = PCB_df.drop('PCB Analytical Method',axis=1)
#PCB_df = PCB_df.drop('PCBs (µg/kg)',axis=1) - keep for explanation


#pull sample id out of index
PCB_df['Sample ID'] = PCB_df.index
#shift column sample ID to first position
first_column = PCB_df.pop('Sample ID')
#insert column using insert(position,column_name,first_column) function
PCB_df.insert(0, 'Sample ID', first_column)



PCB_df

Sample ID,Sample ID,Sample Depth (ft bgs),PCBs (µg/kg),Aroclor-1254,Aroclor-1260
TP-41,TP-41,1-3,µg/kg,NT,NT
TP-42,TP-42,0-2,µg/kg,NT,NT
TP-42.1,TP-42.1,2-4,µg/kg,330 U,330 U
TP-42.1,TP-42.1,2-4,MDL (ug/kg),330,330
TP-44,TP-44,0-3,µg/kg,NT,NT
TP-46,TP-46,2-5,µg/kg,NT,NT
TP-47,TP-47,7.5-9,µg/kg,NT,NT
TP-48,TP-48,3-7,µg/kg,NT,NT
TP-49,TP-49,2-14,µg/kg,NT,NT
TP-51,TP-51,2-10,µg/kg,330 U,330 U
TP-51,TP-51,2-10,MDL (ug/kg),330,330
TP-52,TP-52,6-11.5,µg/kg,330 U,330 U
TP-52,TP-52,6-11.5,MDL (ug/kg),330,330
TP-53,TP-53,2.5-13,µg/kg,330 U,330 U
TP-53,TP-53,2.5-13,MDL (ug/kg),330,330
TP-54,TP-54,3-12,µg/kg,330 U,330 U
TP-54,TP-54,3-12,MDL (ug/kg),330,330
TP-55,TP-55,0-3,µg/kg,330 U,1200
TP-55,TP-55,0-3,MDL (ug/kg),330,330

In [365]:
#make the other analyses table 
misc_df_1 = table_df.iloc[0:1]
#table 5 is 66:70 but all others are 67:71
misc_df_2 = table_df.iloc[66:70,range(0,40,2)]
#misc_df = pd.concat([misc_df_1,misc_df_2])
# #transpose it
# misc_df = misc_df.transpose()
# #make the first row our column titles
# misc_df.columns=misc_df.iloc[0]
# #drop the duplicate row
# misc_df = misc_df.tail(-1)
# #drop middle values of "chemicals columns as they are empty in dataset
# misc_df = misc_df.drop(columns = 'Chemicals')

# # # ##################################################
# # #drop uneccessary columns from misc
# # #misc_df = misc_df.drop(columns=['Sample Depth (ft bgs)'])
# # misc_df.replace(np.nan,0, inplace =True)
# # misc_df['Available Cyanides (ug/kg)'] = np.where(misc_df['Available Cyanides (ug/kg)']==0,'100 U',misc_df['Available Cyanides (ug/kg)'])
# misc_df = misc_df.drop_duplicates()
# #drop rows that didn't get caught as duplicates



#################################################

misc_df_2
#not sure how to incorporate this into data export

,Sample ID,TP-16B,TP-16B.1,TP-16B.1,TP-18,TP-19,TP-19,TP-20,TP-21,TP-21,TP-22,TP-23,TP-23,TP-24,TP-24.1,TP-24.1,TP-25,TP-26,TP-26,TP-27A
66,Chemicals,NaN,Conc.,MDL,NaN,Conc.,MDL,NaN,Conc.,MDL,NaN,Conc.,MDL,NaN,Conc.,MDL,NaN,Conc.,MDL,NaN
67,Percent Moisture (%),NaN,20,0.1,NaN,20,0.1,NaN,22,0.1,NaN,9.1,0.1,NaN,10,0.1,NaN,40,0.1,NaN
68,pH (unitless),NaN,8.95,NaN,NaN,10.6,NaN,NaN,11.45,NaN,NaN,10.88,NaN,NaN,10.99,NaN,NaN,9.87,NaN,NaN
69,Available Cyanides (ug/kg),NaN,NaN,100,NaN,NaN,100,NaN,NaN,100,NaN,NaN,100,NaN,NaN,100,NaN,110,100,NaN

In [105]:
#drop duplicates and keep the first appearance because those are the detections / tests
voc_df = voc_df.drop_duplicates(subset=['Sample Depth (ft bgs)'],keep="first")
BNA_df = BNA_df.drop_duplicates(subset=['Sample ID'], keep="first")
metals_df = metals_df.drop_duplicates(subset=['Sample ID'], keep="first")
PCB_df = PCB_df.drop_duplicates(subset=['Sample ID'], keep="first")
voc_df

#what to do with misc?

Sample ID,Sample ID,Sample Depth (ft bgs),Collection Date,VOCs (µg/kg),Benzene,N-Butylbenzene,Sec-Butylbenzene,Tert-Butylbenzene,Carbon Disulfide,Chlorobenzene,...,Ethylbenzene,Isopropylbenzene,Naphthalene,N-Propylbenzene,Tetrachloroethylene,Toluene,Trichloroethene,"1,2,4-Trimethylbenzene","1,3,5-Trimethylbenzene",Xylene
TP-41,TP-41,1-3,2005-09-27 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-42,TP-42,0-2,2005-09-27 00:00:00,µg/kg,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TP-42.1,TP-42.1,2-4,2005-09-27 00:00:00,µg/kg,NaN,260,94,NaN,NaN,NaN,...,210,NaN,4200,150,NaN,110,NaN,1800,420,1200
TP-44,TP-44,0-3,2005-09-23 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-46,TP-46,2-5,2005-09-23 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-47,TP-47,7.5-9,2005-09-26 00:00:00,µg/kg,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,540,NaN,NaN,NaN,400,110,NaN,260
TP-48,TP-48,3-7,2005-09-26 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-49,TP-49,2-14,2005-09-23 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150
TP-51,TP-51,2-10,2005-09-23 00:00:00,µg/kg,NaN,220,130,NaN,NaN,NaN,...,660,NaN,500,150,NaN,160,160,980,100,2500
TP-52,TP-52,6-11.5,2005-09-24 00:00:00,µg/kg,NaN,230,180,NaN,NaN,NaN,...,62,NaN,1400,160,NaN,180,NaN,150,NaN,290
TP-53,TP-53,2.5-13,2005-09-27 00:00:00,µg/kg,92,120,120,NaN,NaN,NaN,...,370,NaN,430,160,NaN,130,52,350,NaN,1300
TP-54,TP-54,3-12,2005-09-23 00:00:00,MDL (ug/kg),50,50,50,50,250,50,...,50,250,330,100,50,100,50,100,100,150

In [106]:
BNA_df

Sample ID,Sample ID,Sample Depth (ft bgs),BNAs (µg/kg),Benzo(a)Anthracene,Benzo(b)Fluoranthene,Benzo(a)Pyrene,Benzo(ghl)perylene,Benzo(k)Fluoranthene,Chrysene,2-Cloronaphthalene,"2,4-Dimethylphenol",Di-n-octyl phthalate,Fluoranthene,"Indeno(1,2,3-cd)Pyrene",2-Methylnaphthalene,Bis(2-Ethylhexyl)Phthalate,Phenol,Di-n-butyl phthalate,Phenanthrene,Pyrene
TP-41,TP-41,1-3,MDL (ug/kg),1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TP-42,TP-42,0-2,µg/kg,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TP-42.1,TP-42.1,2-4,µg/kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3800,NaN,NaN,1700,NaN,NaN,4300,3600
TP-44,TP-44,0-3,MDL (ug/kg),1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TP-46,TP-46,2-5,µg/kg,3100,NaN,NaN,NaN,NaN,3900,NaN,NaN,NaN,3900,NaN,NaN,NaN,NaN,NaN,NaN,6600
TP-47,TP-47,7.5-9,µg/kg,2100,2900,2100,NaN,NaN,2100,NaN,NaN,NaN,4200,NaN,NaN,NaN,NaN,NaN,3300,4400
TP-48,TP-48,3-7,MDL (ug/kg),330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330
TP-49,TP-49,2-14,µg/kg,NaN,NaN,NaN,NaN,2000,NaN,NaN,NaN,NaN,1900,NaN,NaN,NaN,NaN,NaN,NaN,2100
TP-51,TP-51,2-10,µg/kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1700,NaN,NaN,NaN,NaN,NaN,NaN,1700
TP-52,TP-52,6-11.5,µg/kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1900,NaN,1700,NaN,NaN,NaN,2400,1700
TP-53,TP-53,2.5-13,MDL (ug/kg),1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TP-54,TP-54,3-12,MDL (ug/kg),1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TP-55,TP-55,0-3,MDL (ug/kg),1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700

In [96]:
#split sample depth range into two separate columns
voc_df[['Start_Depth','End_Depth']] = voc_df.get('Sample Depth (ft bgs)').str.split("-",expand=True)


#shift depths to front of df 
first_column = voc_df.pop('Start_Depth')
second_column = voc_df.pop('End_Depth')
  
# insert column using insert(position,column_name,
# first_column) function
voc_df.insert(1, 'Start_Depth', first_column)
voc_df.insert(2, 'End_Depth', second_column)

#drop sample depth range column
voc_df = voc_df.drop(['Sample Depth (ft bgs)'], axis=1)
#drop depth and sample ID in all tables besides voc for merging later
BNA_df = BNA_df.drop(['Sample Depth (ft bgs)'], axis=1)
metals_df = metals_df.drop(['Sample Depth (ft bgs)'], axis=1)
PCB_df = PCB_df.drop(['Sample Depth (ft bgs)'], axis=1)
BNA_df = BNA_df.drop(['Sample ID'], axis=1)
metals_df = metals_df.drop(['Sample ID'], axis=1)
PCB_df = PCB_df.drop(['Sample ID'], axis=1)

#what to do with misc?

C:\Users\fergusonpc\AppData\Local\Temp\ipykernel_10336\2031551684.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  voc_df[['Start_Depth','End_Depth']] = voc_df.get('Sample Depth (ft bgs)').str.split("-",expand=True)
C:\Users\fergusonpc\AppData\Local\Temp\ipykernel_10336\2031551684.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  voc_df[['Start_Depth','End_Depth']] = voc_df.get('Sample Depth (ft bgs)').str.split("-",expand=True)

In [97]:
combined_df = pd.merge(voc_df,BNA_df, left_index = True, right_index = True)
####### voc merge is losing TP-55, check drop duplicates line?
combined_df = pd.merge(combined_df,metals_df, left_index = True, right_index = True)
combined_df = pd.merge(combined_df,PCB_df, left_index = True, right_index = True)
#date conversion must happen in excel due to NT
#combined_df['Collection Date'] = pd.to_datetime(combined_df['Collection Date']).dt.date
combined_df
#what to do with misc?

Sample ID,Sample ID,Start_Depth,End_Depth,Collection Date,VOCs (µg/kg),Benzene,N-Butylbenzene,Sec-Butylbenzene,Tert-Butylbenzene,Carbon Disulfide,...,"Lead, fine fraction","Lead, coarse fraction",Manganese,Mercury,Nickel,Vanadium,Zinc,PCBs (µg/kg),Aroclor-1254,Aroclor-1260
TP-41,TP-41,1,3,2005-09-27 00:00:00,MDL (ug/kg),50,50,50,50,250,...,99000,64400,18000000,NaN,47000,290000,100000,µg/kg,NT,NT
TP-42,TP-42,0,2,2005-09-27 00:00:00,µg/kg,NT,NT,NT,NT,NT,...,334000,136000,11000000,150,34000,200000,730000,µg/kg,NT,NT
TP-42.1,TP-42.1,2,4,2005-09-27 00:00:00,µg/kg,NaN,260,94,NaN,NaN,...,NT,NT,NT,NT,NT,NT,NT,µg/kg,330 U,330 U
TP-44,TP-44,0,3,2005-09-23 00:00:00,MDL (ug/kg),50,50,50,50,250,...,309000,275000,11000000,90,57000,96000,2200000,µg/kg,NT,NT
TP-46,TP-46,2,5,2005-09-23 00:00:00,MDL (ug/kg),50,50,50,50,250,...,320000,200000,6500000,240,29000,58000,240000,µg/kg,NT,NT
TP-47,TP-47,7.5,9,2005-09-26 00:00:00,µg/kg,NaN,NaN,NaN,NaN,NaN,...,536000,368000,400000,760,63000,9600,220000,µg/kg,NT,NT
TP-48,TP-48,3,7,2005-09-26 00:00:00,MDL (ug/kg),50,50,50,50,250,...,33600,6230,190000,NaN,6300,10000,89000,µg/kg,NT,NT
TP-49,TP-49,2,14,2005-09-23 00:00:00,MDL (ug/kg),50,50,50,50,250,...,241000,177000,6100000,200,61000,140000,190000,µg/kg,NT,NT
TP-51,TP-51,2,10,2005-09-23 00:00:00,µg/kg,NaN,220,130,NaN,NaN,...,305000,215000,900000,420,100000,11000,290000,µg/kg,330 U,330 U
TP-52,TP-52,6,11.5,2005-09-24 00:00:00,µg/kg,NaN,230,180,NaN,NaN,...,404000,614000,970000,530,63000,12000,220000,µg/kg,330 U,330 U
TP-53,TP-53,2.5,13,2005-09-27 00:00:00,µg/kg,92,120,120,NaN,NaN,...,70600,42200,610000,230,49000,9000,150000,µg/kg,330 U,330 U
TP-54,TP-54,3,12,2005-09-23 00:00:00,MDL (ug/kg),50,50,50,50,250,...,359000,261000,8200000,510,98000,75000,2000000,µg/kg,330 U,330 U

In [230]:
#export to csv
#change title of table to correspond to the sheet
combined_df.to_csv('table_5_noLF.csv')

In [59]:
#reformatting the original combined df
lf_voc = voc_df.replace(np.nan,0)

#lf_voc.columns.tolist()
#fix combined df for leap frog

#vocs

lf_voc['Benzene '] = np.where((lf_voc['Benzene '] == 50) |(lf_voc['Benzene '] == 0) , '50 U' , lf_voc['Benzene '] )
lf_voc['Benzene LF'] = np.where(lf_voc['Benzene '] == '50 U' , 5 , lf_voc['Benzene '] )

lf_voc['N-Butylbenzene'] = np.where((lf_voc['N-Butylbenzene'] == 50) |(lf_voc['N-Butylbenzene'] == 0) , '50 U' , lf_voc['N-Butylbenzene'] )
lf_voc['N-Butylbenzene LF'] = np.where(lf_voc['N-Butylbenzene'] == '50 U' , 5 , lf_voc['N-Butylbenzene'] )

lf_voc['Sec-Butylbenzene'] = np.where((lf_voc['Sec-Butylbenzene'] == 50) |(lf_voc['Sec-Butylbenzene'] == 0) , '50 U' , lf_voc['Sec-Butylbenzene'] )
lf_voc['Sec-Butylbenzene LF'] = np.where(lf_voc['Sec-Butylbenzene'] == '50 U' , 5 , lf_voc['Sec-Butylbenzene'] )

lf_voc['Tert-Butylbenzene'] = np.where((lf_voc['Tert-Butylbenzene'] == 50) |(lf_voc['Tert-Butylbenzene'] == 0) , '50 U' , lf_voc['Tert-Butylbenzene'] )
lf_voc['Tert-Butylbenzene LF'] = np.where(lf_voc['Tert-Butylbenzene'] == '50 U' , 5 , lf_voc['Tert-Butylbenzene'] )

lf_voc['Carbon Disulfide'] = np.where((lf_voc['Carbon Disulfide'] == 250) |(lf_voc['Carbon Disulfide'] == 0) , '250 U' , lf_voc['Carbon Disulfide'] )
lf_voc['Carbon Disulfide LF'] = np.where(lf_voc['Carbon Disulfide'] == '250 U' , 25 , lf_voc['Carbon Disulfide'] )

lf_voc['Chlorobenzene'] = np.where((lf_voc['Chlorobenzene'] == 50) |(lf_voc['Chlorobenzene'] == 0) , '50 U' , lf_voc['Chlorobenzene'] )
lf_voc['Chlorobenzene LF'] = np.where(lf_voc['Chlorobenzene'] == '50 U' , 5 , lf_voc['Chlorobenzene'] )

lf_voc['1,1-Dichloroethane'] = np.where((lf_voc['1,1-Dichloroethane'] == 50) |(lf_voc['1,1-Dichloroethane'] == 0) , '50 U' , lf_voc['1,1-Dichloroethane'] )
lf_voc['1,1-Dichloroethane LF'] = np.where(lf_voc['1,1-Dichloroethane'] == '50 U' , 5 , lf_voc['1,1-Dichloroethane'] )

lf_voc['cis-1,2-Dichloroethene'] = np.where((lf_voc['cis-1,2-Dichloroethene'] == 50) |(lf_voc['cis-1,2-Dichloroethene'] == 0) , '50 U' , lf_voc['cis-1,2-Dichloroethene'] )
lf_voc['cis-1,2-Dichloroethene LF'] = np.where(lf_voc['cis-1,2-Dichloroethene'] == '50 U' , 5 , lf_voc['cis-1,2-Dichloroethene'] )

lf_voc['Ethylbenzene'] = np.where((lf_voc['Ethylbenzene'] == 50) |(lf_voc['Ethylbenzene'] == 0) , '50 U' , lf_voc['Ethylbenzene'] )
lf_voc['Ethylbenzene LF'] = np.where(lf_voc['Ethylbenzene'] == '50 U' , 5 , lf_voc['Ethylbenzene'] )

lf_voc['Isopropylbenzene'] = np.where((lf_voc['Isopropylbenzene'] == 250) | (lf_voc['Isopropylbenzene'] == 0) , '250 U' , lf_voc['Isopropylbenzene'] )
lf_voc['Isopropylbenzene LF'] = np.where(lf_voc['Isopropylbenzene'] == '250 U' , 25 , lf_voc['Isopropylbenzene'] )

lf_voc['Naphthalene'] = np.where((lf_voc['Naphthalene'] == 330) | (lf_voc['Naphthalene'] == 0) , '330 U' , lf_voc['Naphthalene'] )
lf_voc['Naphthalene LF'] = np.where(lf_voc['Naphthalene'] == '330 U' , 33 , lf_voc['Naphthalene'] )

lf_voc['N-Propylbenzene'] = np.where((lf_voc['N-Propylbenzene'] == 100) | (lf_voc['N-Propylbenzene'] == 0) , '100 U' , lf_voc['N-Propylbenzene'] )
lf_voc['N-Propylbenzene LF'] = np.where(lf_voc['N-Propylbenzene'] == '100 U' , 10 , lf_voc['N-Propylbenzene'] )

lf_voc['Tetrachloroethylene'] = np.where((lf_voc['Tetrachloroethylene'] == 50) | (lf_voc['Tetrachloroethylene'] == 0) , '50 U' , lf_voc['Tetrachloroethylene'] )
lf_voc['Tetrachloroethylene LF'] = np.where(lf_voc['Tetrachloroethylene'] == '50 U' , 5 , lf_voc['Tetrachloroethylene'] )

lf_voc['Toluene'] = np.where((lf_voc['Toluene'] == 100) | (lf_voc['Toluene'] == 0) , '100 U' , lf_voc['Toluene'] )
lf_voc['Toluene LF'] = np.where(lf_voc['Toluene'] == '100 U' , 10 , lf_voc['Toluene'] )

lf_voc['Trichloroethene'] = np.where((lf_voc['Trichloroethene'] == 50) | (lf_voc['Trichloroethene'] == 0) , '50 U' , lf_voc['Trichloroethene'] )
lf_voc['Trichloroethene LF'] = np.where(lf_voc['Trichloroethene'] == '50 U' , 5 , lf_voc['Trichloroethene'] )

lf_voc['1,2,4-Trimethylbenzene'] = np.where((lf_voc['1,2,4-Trimethylbenzene'] == 100) | (lf_voc['1,2,4-Trimethylbenzene'] == 0) , '100 U' , lf_voc['1,2,4-Trimethylbenzene'] )
lf_voc['1,2,4-Trimethylbenzene LF'] = np.where(lf_voc['1,2,4-Trimethylbenzene'] == '100 U' , 10 , lf_voc['1,2,4-Trimethylbenzene'] )

lf_voc['1,3,5-Trimethylbenzene'] = np.where((lf_voc['1,3,5-Trimethylbenzene'] == 100) | (lf_voc['1,3,5-Trimethylbenzene'] == 0) , '100 U' , lf_voc['1,3,5-Trimethylbenzene'] )
lf_voc['1,3,5-Trimethylbenzene LF'] = np.where(lf_voc['1,3,5-Trimethylbenzene'] == '100 U' , 10 , lf_voc['1,3,5-Trimethylbenzene'] )

lf_voc['Xylene'] = np.where((lf_voc['Xylene'] == 150) | (lf_voc['Xylene'] == 0) , '150 U' , lf_voc['Xylene'] )
lf_voc['Xylene LF'] = np.where(lf_voc['Xylene'] == '150 U' , 15 , lf_voc['Xylene'] )

#drop sample ID columns
lf_voc = lf_voc.drop(columns=['Sample ID','VOCs (µg/kg)'])

lf_voc

Sample ID,Start_Depth,End_Depth,Collection Date,Benzene,N-Butylbenzene,Sec-Butylbenzene,Tert-Butylbenzene,Carbon Disulfide,Chlorobenzene,"1,1-Dichloroethane",...,Ethylbenzene LF,Isopropylbenzene LF,Naphthalene LF,N-Propylbenzene LF,Tetrachloroethylene LF,Toluene LF,Trichloroethene LF,"1,2,4-Trimethylbenzene LF","1,3,5-Trimethylbenzene LF",Xylene LF
TP-29,0,8,2005-09-28,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TP-29.1,8,15,2005-09-28,89,2800,1400,88,340,210,50 U,...,1200,1500,4700,2300,76,240,5,17000,5600,9500
TP-30,4,4.5,2005-09-29,50 U,50 U,50 U,50 U,250 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TP-31,0,7,2005-09-28,50 U,50 U,50 U,50 U,250 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TP-32,0.5,2.5,2005-09-29,50 U,50 U,50 U,50 U,250 U,50 U,170,...,5,25,33,10,5,10,180,600,590,400
TP-33,2.5,6,2005-09-29,50 U,50 U,50 U,50 U,250 U,50 U,50 U,...,5,25,33,10,5,10,1300,10,10,180
TP-35,0,3,2005-09-28,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TP-35.1,3,4,2005-09-28,50 U,50 U,50 U,50 U,250 U,50 U,50 U,...,5,25,560,10,5,10,5,10,10,180
TP-36,1.5,3.5,2005-09-28,50 U,50 U,50 U,50 U,250 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,180
TP-37,7,12,2005-09-28,50 U,50 U,50 U,50 U,250 U,50 U,140,...,5,25,560,10,5,10,63,10,10,15
TP-39,0,3.5,2005-09-29,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TP-40,0,4,2005-09-27,50 U,50 U,50 U,50 U,250 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TP-40.1,4,8,2005-09-27,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT

In [232]:
################################################################################################################################
##skip code here because the voc lf separation already done##
################################################################################################################################


# #make the leapfrog inputs for voc
# lf_voc = voc_df.transpose()
# #replace nan w zero
# lf_voc = lf_voc.replace(np.nan,0)

# #isolate depths
# lf_depths = lf_voc.iloc[1:3]

# #isolate dates
# lf_dates = lf_voc.iloc[3]

# #isolate the results
# lf_voc = lf_voc.iloc[5:26]


# lf_voc['TP-16B LF'] = lf_voc['TP-16B']/10
# lf_voc['TP-16B.1 LF'] = lf_voc['TP-16B.1']
# lf_voc['TP-18 LF'] = lf_voc['TP-18']/10
# lf_voc['TP-19 LF'] = np.where(lf_voc['TP-19']>0, lf_voc['TP-19'],lf_voc['TP-18']/10)
# lf_voc['TP-20 LF'] = lf_voc['TP-20']/10
# lf_voc['TP-21 LF'] = lf_voc['TP-21']/10
# lf_voc['TP-22 LF'] = lf_voc['TP-22']/10
# lf_voc['TP-23 LF'] = lf_voc['TP-23']/10
# lf_voc['TP-24 LF'] = lf_voc['TP-24']/10
# lf_voc['TP-24.1 LF'] = lf_voc['TP-24.1']/10
# lf_voc['TP-25 LF'] = lf_voc['TP-25']/10
# lf_voc['TP-26 LF'] = lf_voc['TP-26']/10
# lf_voc['TP-27A LF'] = np.where(lf_voc['TP-27A']>0, lf_voc['TP-27A'],lf_voc['TP-26']/10)


# #isolate lf values
# lf_voc = lf_voc.iloc[:,13:26]
# #lf_voc = lf_voc.transpose()

# lf_depths = lf_depths.rename(columns={'TP-16B':'TP-16B LF','TP-16B.1':'TP-16B.1 LF',
#                        'TP-18':'TP-18 LF','TP-19':'TP-19 LF',
#                        'TP-20':'TP-20 LF','TP-21':'TP-21 LF',
#                        'TP-22':'TP-22 LF','TP-23':'TP-23 LF',
#                        'TP-24':'TP-24 LF','TP-24.1':'TP-24.1 LF','TP-25':'TP-25 LF',
#                        'TP-26':'TP-26 LF','TP-27A':'TP-27A LF'})
# # lf_dates = lf_dates.rename(columns={'TP-16B':'TP-16B LF','TP-16B.1':'TP-16B.1 LF',
# #                        'TP-18':'TP-18 LF','TP-19':'TP-19 LF',
# #                        'TP-20':'TP-20 LF','TP-21':'TP-21 LF',
# #                        'TP-22':'TP-22 LF','TP-23':'TP-23 LF',
# #                        'TP-24':'TP-24 LF','TP-24.1':'TP-24.1 LF','TP-25':'TP-25 LF',
# #                        'TP-26':'TP-26 LF','TP-27A':'TP-27A LF'})


# #add on depths
# lf_voc = pd.concat([lf_voc,lf_depths])

# #add on dates
# #lf_voc = pd.concat([lf_voc,lf_dates])

# #transpose for export
# lf_voc = lf_voc.transpose()
# lf_voc

# #merge the LF data with non_lf data

In [77]:
#make the leapfrog inputs for BNA
lf_BNA = BNA_df.transpose()
#replace nan w zero
lf_BNA = lf_BNA.replace(np.nan,0)



#isolate the results
lf_BNA = lf_BNA.iloc[1:]


#in table 7 fix columns w detections
#fix column TP-29 and TP-35.1 in table 7
lf_BNA['TP-29.1'] = np.where(lf_BNA['TP-29.1']>0, lf_BNA['TP-29.1'],'1700 U')
lf_BNA['TP-35.1'] = np.where(lf_BNA['TP-35.1']>0, lf_BNA['TP-35.1'],'1700 U')

###################################################
#account for different mdls in table 5
#for table 5
# lf_BNA['TP-25'] = np.where(lf_BNA['TP-25']==1700,'1700 U',lf_BNA['TP-25'])
# lf_BNA['TP-26'] = np.where(lf_BNA['TP-26']>0, lf_BNA['TP-26'],'1700 U')
# lf_BNA['TP-27A'] = np.where(lf_BNA['TP-27A']>0, lf_BNA['TP-27A'],'1700 U')
###################################################

# #add U to all undetects


###################################################
#for table 5
#add U to all undetects
# lf_BNA['TP-16B'] = np.where(lf_BNA['TP-16B']==1700,'1700 U',lf_BNA['TP-16B'])
# lf_BNA['TP-18'] = np.where(lf_BNA['TP-18']==330, '330 U',lf_BNA['TP-18'])
# lf_BNA['TP-19'] = np.where(lf_BNA['TP-19']==1700,'1700 U',lf_BNA['TP-19'])
# lf_BNA['TP-20'] = np.where(lf_BNA['TP-20']==1700,'1700 U',lf_BNA['TP-20'])
# lf_BNA['TP-21'] = np.where(lf_BNA['TP-21']==330,'330 U',lf_BNA['TP-21'])
# lf_BNA['TP-22'] = np.where(lf_BNA['TP-22']==1700,'1700 U',lf_BNA['TP-22'])
# lf_BNA['TP-23'] = np.where(lf_BNA['TP-23']==330,'330 U',lf_BNA['TP-23'])
# lf_BNA['TP-24'] = np.where(lf_BNA['TP-24']==1700,'1700 U',lf_BNA['TP-24'])
###################################################

###################################################
#for table 7
#add U to all undetects
lf_BNA['TP-30'] = np.where(lf_BNA['TP-30']==1700,'1700 U',lf_BNA['TP-30'])
lf_BNA['TP-31'] = np.where(lf_BNA['TP-31']==1700,'1700 U',lf_BNA['TP-31'])
lf_BNA['TP-32'] = np.where(lf_BNA['TP-32']==1700,'1700 U',lf_BNA['TP-32'])
lf_BNA['TP-33'] = np.where(lf_BNA['TP-33']==1700,'1700 U',lf_BNA['TP-33'])
lf_BNA['TP-36'] = np.where(lf_BNA['TP-36']==1700,'1700 U',lf_BNA['TP-36'])
lf_BNA['TP-37'] = np.where(lf_BNA['TP-37']==1700,'1700 U',lf_BNA['TP-37'])
lf_BNA['TP-40'] = np.where(lf_BNA['TP-40']==1700,'1700 U',lf_BNA['TP-40'])
###################################################


#flip for merging
lf_BNA = lf_BNA.transpose()

#add lf values for BNAs

#for table 7
#change MDLs to match data table
lf_BNA['Benzo(a)Anthracene LF'] = np.where(lf_BNA['Benzo(a)Anthracene']=='1700 U', 170 ,lf_BNA['Benzo(a)Anthracene'])

lf_BNA['Benzo(b)Fluoranthene LF'] = np.where(lf_BNA['Benzo(b)Fluoranthene']=='1700 U', 170 ,lf_BNA['Benzo(b)Fluoranthene'])

lf_BNA['Benzo(ghl)perylene LF'] = np.where(lf_BNA['Benzo(ghl)perylene']=='1700 U', 170 ,lf_BNA['Benzo(ghl)perylene'])

lf_BNA['Benzo(a)Pyrene LF'] = np.where(lf_BNA['Benzo(a)Pyrene']=='1700 U', 170 ,lf_BNA['Benzo(a)Pyrene'])

lf_BNA['Chrysene LF'] = np.where(lf_BNA['Chrysene']=='1700 U', 170 ,lf_BNA['Chrysene'])

lf_BNA['2-Cloronaphthalene LF'] = np.where(lf_BNA['2-Cloronaphthalene']=='1700 U', 170 ,lf_BNA['2-Cloronaphthalene'])

lf_BNA['2,4-Dimethylphenol LF'] = np.where(lf_BNA['2,4-Dimethylphenol']=='1700 U', 170 ,lf_BNA['2,4-Dimethylphenol'])

lf_BNA['Di-n-octyl phthalate LF'] = np.where(lf_BNA['Di-n-octyl phthalate']=='1700 U', 170 ,lf_BNA['Di-n-octyl phthalate'])

lf_BNA['Fluoranthene LF'] = np.where(lf_BNA['Fluoranthene']=='1700 U', 170 ,lf_BNA['Fluoranthene'])

lf_BNA['Indeno(1,2,3-cd)Pyrene LF'] = np.where(lf_BNA['Indeno(1,2,3-cd)Pyrene']=='1700 U', 170 ,lf_BNA['Indeno(1,2,3-cd)Pyrene'])

lf_BNA['2-Methylnaphthalene LF'] = np.where(lf_BNA['2-Methylnaphthalene']=='1700 U', 170 ,lf_BNA['2-Methylnaphthalene'])

lf_BNA['Bis(2-Ethylhexyl)Phthalate LF'] = np.where(lf_BNA['Bis(2-Ethylhexyl)Phthalate']=='1700 U', 170 ,lf_BNA['Bis(2-Ethylhexyl)Phthalate'])

lf_BNA['Phenol LF'] = np.where(lf_BNA['Phenol']=='1700 U', 170 ,lf_BNA['Phenol'])

lf_BNA['Di-n-butyl phthalate LF'] = np.where(lf_BNA['Di-n-butyl phthalate']=='1700 U', 170 ,lf_BNA['Di-n-butyl phthalate'])

lf_BNA['Phenanthrene LF'] = np.where(lf_BNA['Phenanthrene']=='1700 U', 170 ,lf_BNA['Phenanthrene'])

lf_BNA['Pyrene LF'] = np.where(lf_BNA['Pyrene']=='1700 U', 170 ,lf_BNA['Pyrene'])

######################################################
#for table 5
# #change MDLs to match data table
# lf_BNA['Benzo(a)Anthracene LF'] = np.where(lf_BNA['Benzo(a)Anthracene']=='1700 U', 170 ,lf_BNA['Benzo(a)Anthracene'])
# lf_BNA['Benzo(a)Anthracene LF'] = np.where(lf_BNA['Benzo(a)Anthracene LF']=='330 U', 33 ,lf_BNA['Benzo(a)Anthracene LF'])

# lf_BNA['Benzo(b)Fluoranthene LF'] = np.where(lf_BNA['Benzo(b)Fluoranthene']=='1700 U', 170 ,lf_BNA['Benzo(b)Fluoranthene'])
# lf_BNA['Benzo(b)Fluoranthene LF'] = np.where(lf_BNA['Benzo(b)Fluoranthene LF']=='330 U', 33 ,lf_BNA['Benzo(b)Fluoranthene LF'])

# lf_BNA['Benzo(a)Pyrene LF'] = np.where(lf_BNA['Benzo(a)Pyrene']=='1700 U', 170 ,lf_BNA['Benzo(a)Pyrene'])
# lf_BNA['Benzo(a)Pyrene LF'] = np.where(lf_BNA['Benzo(a)Pyrene LF']=='330 U', 33 ,lf_BNA['Benzo(a)Pyrene LF'])

# lf_BNA['Chrysene LF'] = np.where(lf_BNA['Chrysene']=='1700 U', 170 ,lf_BNA['Chrysene'])
# lf_BNA['Chrysene LF'] = np.where(lf_BNA['Chrysene LF']=='330 U', 33 ,lf_BNA['Chrysene LF'])

# lf_BNA['2-Cloronaphthalene LF'] = np.where(lf_BNA['2-Cloronaphthalene']=='1700 U', 170 ,lf_BNA['2-Cloronaphthalene'])
# lf_BNA['2-Cloronaphthalene LF'] = np.where(lf_BNA['2-Cloronaphthalene LF']=='330 U', 33 ,lf_BNA['2-Cloronaphthalene LF'])

# lf_BNA['2,4-Dimethylphenol LF'] = np.where(lf_BNA['2,4-Dimethylphenol']=='1700 U', 170 ,lf_BNA['2,4-Dimethylphenol'])
# lf_BNA['2,4-Dimethylphenol LF'] = np.where(lf_BNA['2,4-Dimethylphenol LF']=='330 U', 33 ,lf_BNA['2,4-Dimethylphenol LF'])

# lf_BNA['Di-n-octyl phthalate LF'] = np.where(lf_BNA['Di-n-octyl phthalate']=='1700 U', 170 ,lf_BNA['Di-n-octyl phthalate'])
# lf_BNA['Di-n-octyl phthalate LF'] = np.where(lf_BNA['Di-n-octyl phthalate LF']=='330 U', 33 ,lf_BNA['Di-n-octyl phthalate LF'])

# lf_BNA['Fluoranthene LF'] = np.where(lf_BNA['Fluoranthene']=='1700 U', 170 ,lf_BNA['Fluoranthene'])
# lf_BNA['Fluoranthene LF'] = np.where(lf_BNA['Fluoranthene LF']=='330 U', 33 ,lf_BNA['Fluoranthene LF'])

# lf_BNA['Indeno(1,2,3-cd)Pyrene LF'] = np.where(lf_BNA['Indeno(1,2,3-cd)Pyrene']=='1700 U', 170 ,lf_BNA['Indeno(1,2,3-cd)Pyrene'])
# lf_BNA['Indeno(1,2,3-cd)Pyrene LF'] = np.where(lf_BNA['Indeno(1,2,3-cd)Pyrene LF']=='330 U', 33 ,lf_BNA['Indeno(1,2,3-cd)Pyrene LF'])

# lf_BNA['2-Methylnaphthalene LF'] = np.where(lf_BNA['2-Methylnaphthalene']=='1700 U', 170 ,lf_BNA['2-Methylnaphthalene'])
# lf_BNA['2-Methylnaphthalene LF'] = np.where(lf_BNA['2-Methylnaphthalene LF']=='330 U', 33 ,lf_BNA['2-Methylnaphthalene LF'])

# lf_BNA['Bis(2-Ethylhexyl)Phthalate LF'] = np.where(lf_BNA['Bis(2-Ethylhexyl)Phthalate']=='1700 U', 170 ,lf_BNA['Bis(2-Ethylhexyl)Phthalate'])
# lf_BNA['Bis(2-Ethylhexyl)Phthalate LF'] = np.where(lf_BNA['Bis(2-Ethylhexyl)Phthalate LF']=='330 U', 33 ,lf_BNA['Bis(2-Ethylhexyl)Phthalate LF'])

# lf_BNA['Phenol LF'] = np.where(lf_BNA['Phenol']=='1700 U', 170 ,lf_BNA['Phenol'])
# lf_BNA['Phenol LF'] = np.where(lf_BNA['Phenol LF']=='330 U', 33 ,lf_BNA['Phenol LF'])

# lf_BNA['Di-n-butyl phthalate LF'] = np.where(lf_BNA['Di-n-butyl phthalate']=='1700 U', 170 ,lf_BNA['Di-n-butyl phthalate'])
# lf_BNA['Di-n-butyl phthalate LF'] = np.where(lf_BNA['Di-n-butyl phthalate LF']=='330 U', 33 ,lf_BNA['Di-n-butyl phthalate LF'])

# lf_BNA['Phenanthrene LF'] = np.where(lf_BNA['Phenanthrene']=='1700 U', 170 ,lf_BNA['Phenanthrene'])
# lf_BNA['Phenanthrene LF'] = np.where(lf_BNA['Phenanthrene LF']=='330 U', 33 ,lf_BNA['Phenanthrene LF'])

# lf_BNA['Pyrene LF'] = np.where(lf_BNA['Pyrene']=='1700 U', 170 ,lf_BNA['Pyrene'])
# lf_BNA['Pyrene LF'] = np.where(lf_BNA['Pyrene LF']=='330 U', 33 ,lf_BNA['Pyrene LF'])
######################################################



lf_BNA

Sample ID,Benzo(a)Anthracene,Benzo(b)Fluoranthene,Benzo(a)Pyrene,Benzo(ghl)perylene,Benzo(k)Fluoranthene,Chrysene,2-Cloronaphthalene,"2,4-Dimethylphenol",Di-n-octyl phthalate,Fluoranthene,...,"2,4-Dimethylphenol LF",Di-n-octyl phthalate LF,Fluoranthene LF,"Indeno(1,2,3-cd)Pyrene LF",2-Methylnaphthalene LF,Bis(2-Ethylhexyl)Phthalate LF,Phenol LF,Di-n-butyl phthalate LF,Phenanthrene LF,Pyrene LF
TP-29,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TP-29.1,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1800,1700 U,1700 U,...,1800,170,170,170,4400,170,170,170,1900,170
TP-30,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TP-31,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TP-32,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TP-33,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TP-35,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TP-35.1,2500,3200,2400,1700 U,1700 U,2400,1700 U,1700 U,1700 U,4800,...,170,170,4800,170,170,170,170,170,3300,3900
TP-36,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TP-37,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TP-39,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TP-40,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TP-40.1,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT

In [78]:
#make the leapfrog inputs for metals
lf_metals = metals_df
#replace nan w zero
lf_metals = lf_metals.replace(np.nan,0)

#isolate the results
lf_metals = lf_metals.iloc[0:]

#fix mercury non detect
lf_metals['Mercury'] = np.where(lf_metals['Mercury']==0, f'50' + ' U' , lf_metals['Mercury'])
#add mercury LF column
lf_metals['Mercury LF'] = np.where(lf_metals['Mercury']=='50 U', 5 , lf_metals['Mercury'])
# fix Chromium IV nondetect
lf_metals['Chromium IV'] = np.where(lf_metals['Chromium IV']==0, f'500' + ' U' , lf_metals['Chromium IV'])
#add mercury LF column
lf_metals['Chromium IV LF'] = np.where(lf_metals['Chromium IV']=='500 U', 50 , lf_metals['Chromium IV'])

lf_metals

Sample ID,Metals (µg/kg),Arsenic,Barium,Cadmium,Chromium,Chromium IV,"Lead, total (calculated)","Lead, fine fraction","Lead, coarse fraction",Manganese,Mercury,Nickel,Vanadium,Zinc,Mercury LF,Chromium IV LF
TP-29,µg/kg,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TP-29.1,µg/kg,5700,430000,9900,57000,500 U,118000,172000,116000,920000,230,230000,7300,90000,230,50
TP-30,µg/kg,6100,250000,2400,100000,500 U,26900,88500,24800,1000000,110,230000,12000,450000,110,50
TP-31,µg/kg,5800,200000,1300,130000,500 U,56200,105000,54000,5400000,64,27000,44000,110000,64,50
TP-32,µg/kg,2800,230000,400,98000,500 U,43300,100000,41800,4400000,170,13000,26000,44000,170,50
TP-33,µg/kg,4200,160000,2000,74000,500 U,141000,210000,103000,2000000,160,56000,15000,490000,160,50
TP-35,µg/kg,2300,310000,140,46000,500 U,33900,48300,19500,3300000,50 U,4600,31000,55000,5,50
TP-35.1,µg/kg,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TP-36,µg/kg,4900,130000,3500,55000,500 U,32900,29300,34000,660000,310,57000,11000,330000,310,50
TP-37,µg/kg,2800,93000,5600,59000,500 U,145000,441000,132000,1900000,330,17000,15000,73000,330,50
TP-39,µg/kg,5200,220000,1900,90000,500 U,143000,238000,113000,1800000,250,79000,27000,330000,250,50
TP-40,µg/kg,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TP-40.1,µg/kg,6300,42000,220,18000,500 U,4490,37400,3390,490000,50 U,13000,16000,99000,5,50

In [80]:
#make the leapfrog inputs for PCBs
lf_PCB = PCB_df
#replace nan w zero
lf_PCB = lf_PCB.replace(np.nan,0)




#isolate the results
lf_PCB = lf_PCB.iloc[0:].drop(columns = lf_PCB.columns[0])

#add leapfrog input for PCBs
lf_PCB['Aroclor-1254 LF'] = np.where(lf_PCB['Aroclor-1254'] == '330 U', 3.3 ,lf_PCB['Aroclor-1254'])
lf_PCB['Aroclor-1260 LF'] = np.where(lf_PCB['Aroclor-1260'] == '330 U', 3.3 ,lf_PCB['Aroclor-1260'])

lf_PCB

Sample ID Aroclor-1254 Aroclor-1260 Aroclor-1254 LF Aroclor-1260 LF
TP-29            330 U        330 U             3.3             3.3
TP-29.1          330 U        330 U             3.3             3.3
TP-30               NT           NT              NT              NT
TP-31             1300        330 U            1300             3.3
TP-32            330 U        330 U             3.3             3.3
TP-33               NT           NT              NT              NT
TP-35               NT           NT              NT              NT
TP-35.1             NT           NT              NT              NT
TP-36               NT           NT              NT              NT
TP-37               NT           NT              NT              NT
TP-39               NT           NT              NT              NT
TP-40            330 U        330 U             3.3             3.3
TP-40.1             NT           NT              NT              NT

In [81]:
combined_lf= pd.merge(lf_BNA,lf_metals, left_index = True, right_index = True)
combined_lf= pd.merge(combined_lf,lf_PCB, left_index = True, right_index = True)
combined_lf= pd.merge(combined_lf,lf_voc, left_index = True, right_index = True)



#shift depths and date to front of df 
first_column = combined_lf.pop('Start_Depth')
second_column = combined_lf.pop('End_Depth')
third_column = combined_lf.pop('Collection Date')

#sort columns alphabetically
combined_lf = combined_lf.sort_index(axis = 1, ascending = True)
  
#insert column using insert(position,column_name,first_column) function
combined_lf.insert(0, 'Start_Depth', first_column)
combined_lf.insert(1, 'End_Depth', second_column)
combined_lf.insert(2, 'Sample_Date', third_column)

#setindex name
combined_lf.index.name='Sample_ID'

combined_lf

Sample ID,Start_Depth,End_Depth,Sample_Date,"1,1-Dichloroethane","1,1-Dichloroethane LF","1,2,4-Trimethylbenzene","1,2,4-Trimethylbenzene LF","1,3,5-Trimethylbenzene","1,3,5-Trimethylbenzene LF","2,4-Dimethylphenol",...,Toluene,Toluene LF,Trichloroethene,Trichloroethene LF,Vanadium,Xylene,Xylene LF,Zinc,"cis-1,2-Dichloroethene","cis-1,2-Dichloroethene LF"
Sample_ID,,,,,,,,,,,,,,,,,,,,,
TP-29,0,8,2005-09-28,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TP-29.1,8,15,2005-09-28,50 U,5,17000,17000,5600,5600,1800,...,240,240,50 U,5,7300,9500,9500,90000,50 U,5
TP-30,4,4.5,2005-09-29,50 U,5,100 U,10,100 U,10,1700 U,...,100 U,10,50 U,5,12000,150 U,15,450000,50 U,5
TP-31,0,7,2005-09-28,50 U,5,100 U,10,100 U,10,1700 U,...,100 U,10,50 U,5,44000,150 U,15,110000,50 U,5
TP-32,0.5,2.5,2005-09-29,170,170,600,600,590,590,1700 U,...,100 U,10,180,180,26000,400,400,44000,50 U,5
TP-33,2.5,6,2005-09-29,50 U,5,100 U,10,100 U,10,1700 U,...,100 U,10,1300,1300,15000,180,180,490000,74,74
TP-35,0,3,2005-09-28,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,31000,NT,NT,55000,NT,NT
TP-35.1,3,4,2005-09-28,50 U,5,100 U,10,100 U,10,1700 U,...,100 U,10,50 U,5,NT,180,180,NT,50 U,5
TP-36,1.5,3.5,2005-09-28,50 U,5,100 U,10,100 U,10,1700 U,...,100 U,10,50 U,5,11000,180,180,330000,50 U,5
TP-37,7,12,2005-09-28,140,140,100 U,10,100 U,10,1700 U,...,100 U,10,63,63,15000,150 U,15,73000,50 U,5
TP-39,0,3.5,2005-09-29,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,27000,NT,NT,330000,NT,NT
TP-40,0,4,2005-09-27,50 U,5,100 U,10,100 U,10,1700 U,...,100 U,10,50 U,5,NT,150 U,15,NT,50 U,5
TP-40.1,4,8,2005-09-27,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,16000,NT,NT,99000,NT,NT

In [82]:
combined_lf.to_csv("LeapFrog Exports/table_7_final.csv")