In [1]:
import pandas as pd
import numpy as np

In [2]:
table = "NTH Soil data 2005_PF.xlsx"

In [3]:
#run this across each sheet of the file
table_df = pd.read_excel(table, sheet_name = 1)
table_df

,Sample ID,TB-N122,Unnamed: 2,Unnamed: 3,TB-N124,Unnamed: 5,Unnamed: 6,TB-N125,Unnamed: 8,Unnamed: 9,...,Unnamed: 33,TB-N131,Unnamed: 35,Unnamed: 36,TB-N132,Unnamed: 38,Unnamed: 39,TB-N132.1,Unnamed: 41,Unnamed: 42
0,Sample Depth (ft bgs),1-3,NaN,NaN,8-10,NaN,NaN,5.5-7.5,NaN,NaN,...,NaN,3-5,NaN,NaN,3-5,NaN,NaN,5.5-7.5,NaN,NaN
1,Collection Date,2005-09-22 00:00:00,NaN,NaN,2005-09-28 00:00:00,NaN,NaN,2005-09-28 00:00:00,NaN,NaN,...,NaN,2005-09-22 00:00:00,NaN,NaN,2005-09-28 00:00:00,NaN,NaN,2005-09-28 00:00:00,NaN,NaN
2,VOC Analysis Date,2005-09-30 00:00:00,NaN,NaN,2005-10-06 00:00:00,NaN,NaN,NT,NaN,NaN,...,NaN,2005-09-30 00:00:00,NaN,NaN,NT,NaN,NaN,2005-10-07 00:00:00,NaN,NaN
3,VOC Extraction Date,2005-09-22 00:00:00,NaN,NaN,2005-09-28 00:00:00,NaN,NaN,NT,NaN,NaN,...,NaN,2005-09-22 00:00:00,NaN,NaN,NT,NaN,NaN,2005-09-28 00:00:00,NaN,NaN
4,VOC Analytical Method,SW846 8260B,NaN,NaN,SW846 8260B,NaN,NaN,NT,NaN,NaN,...,NaN,SW846 8260B,NaN,NaN,NT,NaN,NaN,SW846 8260B,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,PCB = polychlorinated biphenyl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,TB = test boring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Âµg/kg = microgram per kilogram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,VOC = volatile organic compound,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#replace - with NA for dropping purposes
table_df = table_df.replace('â',np.nan)

#fix the unnamed columns

for i in list(range(1,len(table_df.columns),3)):
    
    #rename columns
    newCol1 = str(table_df.columns.tolist()[i])
    newCol2 = str(table_df.columns.tolist()[i])
    table_df.iat[0,i+1]  = table_df.iat[0,i]
    table_df.iat[0,i+2]  = table_df.iat[0,i]
    table_df.iat[1,i+1]  = table_df.iat[1,i]
    table_df.iat[1,i+2]  = table_df.iat[1,i]
    table_df.iat[2,i+1]  = table_df.iat[2,i]
    table_df.iat[2,i+2]  = table_df.iat[2,i]
    table_df.iat[3,i+1]  = table_df.iat[3,i]
    table_df.iat[3,i+2]  = table_df.iat[3,i]
    table_df = table_df.rename(columns = {table_df.columns.to_list()[i+1]:newCol1})
    table_df = table_df.rename(columns = {table_df.columns.to_list()[i+2]:newCol2})
   # print(i)
table_df

,Sample ID,TB-N122,TB-N122,TB-N122,TB-N124,TB-N124,TB-N124,TB-N125,TB-N125,TB-N125,...,TB-N130.1,TB-N131,TB-N131,TB-N131,TB-N132,TB-N132,TB-N132,TB-N132.1,TB-N132.1,TB-N132.1
0,Sample Depth (ft bgs),1-3,1-3,1-3,8-10,8-10,8-10,5.5-7.5,5.5-7.5,5.5-7.5,...,10.5-12.5,3-5,3-5,3-5,3-5,3-5,3-5,5.5-7.5,5.5-7.5,5.5-7.5
1,Collection Date,2005-09-22 00:00:00,2005-09-22 00:00:00,2005-09-22 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,...,2005-09-23 00:00:00,2005-09-22 00:00:00,2005-09-22 00:00:00,2005-09-22 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00
2,VOC Analysis Date,2005-09-30 00:00:00,2005-09-30 00:00:00,2005-09-30 00:00:00,2005-10-06 00:00:00,2005-10-06 00:00:00,2005-10-06 00:00:00,NT,NT,NT,...,2005-10-01 00:00:00,2005-09-30 00:00:00,2005-09-30 00:00:00,2005-09-30 00:00:00,NT,NT,NT,2005-10-07 00:00:00,2005-10-07 00:00:00,2005-10-07 00:00:00
3,VOC Extraction Date,2005-09-22 00:00:00,2005-09-22 00:00:00,2005-09-22 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,NT,NT,NT,...,2005-09-23 00:00:00,2005-09-22 00:00:00,2005-09-22 00:00:00,2005-09-22 00:00:00,NT,NT,NT,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00
4,VOC Analytical Method,SW846 8260B,NaN,NaN,SW846 8260B,NaN,NaN,NT,NaN,NaN,...,NaN,SW846 8260B,NaN,NaN,NT,NaN,NaN,SW846 8260B,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,PCB = polychlorinated biphenyl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,TB = test boring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Âµg/kg = microgram per kilogram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,VOC = volatile organic compound,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#isolate VOC data
voc_df = table_df.iloc[:22]

##################################################
#transpose it
voc_df = voc_df.transpose()
#make the first row our column titles
voc_df.columns=voc_df.iloc[0]
#drop the duplicate row
voc_df = voc_df.tail(-1)
#drop samples with no detections
voc_df = voc_df.dropna(thresh=4)
##################################################

voc_df.index.name = None

# ###########################################

# #drop VOC details for mergining
voc_df = voc_df.drop('VOC Analysis Date',axis=1)
voc_df = voc_df.drop('VOC Analytical Method',axis=1)
voc_df = voc_df.drop('VOC Extraction Date',axis=1)
voc_df = voc_df.drop('VOCs',axis=1) # bring back for explanation if necessary

#pull sample id out of index
voc_df['Sample ID'] = voc_df.index

#shift column sample ID to first position
first_column = voc_df.pop('Sample ID')
#insert column using insert(position,column_name,first_column) function
voc_df.insert(0, 'Sample ID', first_column)




#drop duplicates and keep the first appearance because those are the detections / tests
voc_df = voc_df.drop_duplicates(subset=['Sample ID'],keep="first")

#split sample depth range into two separate columns
voc_df[['Start_Depth','End_Depth']] = voc_df.get('Sample Depth (ft bgs)').str.split("-",expand=True)

#shift depths to front of df 
first_column = voc_df.pop('Start_Depth')
second_column = voc_df.pop('End_Depth')
  
# insert column using insert(position,column_name,
# first_column) function
voc_df.insert(1, 'Start_Depth', first_column)
voc_df.insert(2, 'End_Depth', second_column)

#drop sample ID and depth range
voc_df = voc_df.drop(['Sample ID'], axis=1)
voc_df = voc_df.drop(['Sample Depth (ft bgs)'], axis=1)

#rename voc columns
voc_df = voc_df.rename(columns = {'Collection Date':'Sample_Date'})

voc_df
#change format of date to eliminate the time?

Sample ID,Start_Depth,End_Depth,Sample_Date,Benzene,n-Butylbenzene,sec-Butylbenzene,Chlorobenzene,"1,1-Dichloroethane","cis-1,2-Dichloroethene",Ethylbenzene,Isopropylbenzene,Naphthalene,n-Propylbenzene,Tetrachloroethylene,Toluene,Trichloroethene,"1,2,4-Trimethylbenzene","1,3,5-Trimethylbenzene",Xylenes
TB-N122,1,3,2005-09-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TB-N124,8,10,2005-09-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TB-N125,5.5,7.5,2005-09-28 00:00:00,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N125.1,13,15,2005-09-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TB-N126,0.5,2.5,2005-09-28 00:00:00,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N126.1,5.5,7.5,2005-09-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TB-N127,8,10,2005-09-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TB-N128,4,6,2005-09-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TB-N129,10.5,12.5,2005-09-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TB-N130,0.5,2.5,2005-09-23 00:00:00,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N130.1,10.5,12.5,2005-09-23 00:00:00,55,NaN,NaN,NaN,NaN,210,160,NaN,NaN,NaN,NaN,NaN,140,140,NaN,600
TB-N131,3,5,2005-09-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TB-N132,3,5,2005-09-28 00:00:00,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N132.1,5.5,7.5,2005-09-28 00:00:00,83,160,160,340,290,56,330,NaN,NaN,280,NaN,NaN,100,150,NaN,580

In [6]:
#adjust voc_df for leapfrog input
#reformatting the original combined df
lf_voc = voc_df.replace(np.nan,0)

#vocs

lf_voc['Benzene '] = np.where((lf_voc['Benzene '] == 50) |(lf_voc['Benzene '] == 0) , '50 U' , lf_voc['Benzene '] )
lf_voc['Benzene LF'] = np.where(lf_voc['Benzene '] == '50 U' , 5 , lf_voc['Benzene '] )

lf_voc['n-Butylbenzene'] = np.where((lf_voc['n-Butylbenzene'] == 50) |(lf_voc['n-Butylbenzene'] == 0) , '50 U' , lf_voc['n-Butylbenzene'] )
lf_voc['n-Butylbenzene LF'] = np.where(lf_voc['n-Butylbenzene'] == '50 U' , 5 , lf_voc['n-Butylbenzene'] )

lf_voc['sec-Butylbenzene'] = np.where((lf_voc['sec-Butylbenzene'] == 50) |(lf_voc['sec-Butylbenzene'] == 0) , '50 U' , lf_voc['sec-Butylbenzene'] )
lf_voc['sec-Butylbenzene LF'] = np.where(lf_voc['sec-Butylbenzene'] == '50 U' , 5 , lf_voc['sec-Butylbenzene'] )

#not in this data
# lf_voc['Tert-Butylbenzene'] = np.where((lf_voc['tert-Butylbenzene'] == 50) |(lf_voc['tert-Butylbenzene'] == 0) , '50 U' , lf_voc['tert-Butylbenzene'] )
# lf_voc['Tert-Butylbenzene LF'] = np.where(lf_voc['tert-Butylbenzene'] == '50 U' , 5 , lf_voc['tert-Butylbenzene'] )

#not in this data
# lf_voc['Carbon Disulfide'] = np.where((lf_voc['Carbon Disulfide'] == 250) |(lf_voc['Carbon Disulfide'] == 0) , '250 U' , lf_voc['Carbon Disulfide'] )
# lf_voc['Carbon Disulfide LF'] = np.where(lf_voc['Carbon Disulfide'] == '250 U' , 25 , lf_voc['Carbon Disulfide'] )

lf_voc['Chlorobenzene'] = np.where((lf_voc['Chlorobenzene'] == 50) |(lf_voc['Chlorobenzene'] == 0) , '50 U' , lf_voc['Chlorobenzene'] )
lf_voc['Chlorobenzene LF'] = np.where(lf_voc['Chlorobenzene'] == '50 U' , 5 , lf_voc['Chlorobenzene'] )

lf_voc['1,1-Dichloroethane'] = np.where((lf_voc['1,1-Dichloroethane'] == 50) |(lf_voc['1,1-Dichloroethane'] == 0) , '50 U' , lf_voc['1,1-Dichloroethane'] )
lf_voc['1,1-Dichloroethane LF'] = np.where(lf_voc['1,1-Dichloroethane'] == '50 U' , 5 , lf_voc['1,1-Dichloroethane'] )

lf_voc['cis-1,2-Dichloroethene'] = np.where((lf_voc['cis-1,2-Dichloroethene'] == 50) |(lf_voc['cis-1,2-Dichloroethene'] == 0) , '50 U' , lf_voc['cis-1,2-Dichloroethene'] )
lf_voc['cis-1,2-Dichloroethene LF'] = np.where(lf_voc['cis-1,2-Dichloroethene'] == '50 U' , 5 , lf_voc['cis-1,2-Dichloroethene'] )

lf_voc['Ethylbenzene'] = np.where((lf_voc['Ethylbenzene'] == 50) |(lf_voc['Ethylbenzene'] == 0) , '50 U' , lf_voc['Ethylbenzene'] )
lf_voc['Ethylbenzene LF'] = np.where(lf_voc['Ethylbenzene'] == '50 U' , 5 , lf_voc['Ethylbenzene'] )

lf_voc['Isopropylbenzene'] = np.where((lf_voc['Isopropylbenzene'] == 250) | (lf_voc['Isopropylbenzene'] == 0) , '250 U' , lf_voc['Isopropylbenzene'] )
lf_voc['Isopropylbenzene LF'] = np.where(lf_voc['Isopropylbenzene'] == '250 U' , 25 , lf_voc['Isopropylbenzene'] )

lf_voc['Naphthalene'] = np.where((lf_voc['Naphthalene'] == 330) | (lf_voc['Naphthalene'] == 0) , '330 U' , lf_voc['Naphthalene'] )
lf_voc['Naphthalene LF'] = np.where(lf_voc['Naphthalene'] == '330 U' , 33 , lf_voc['Naphthalene'] )

lf_voc['n-Propylbenzene'] = np.where((lf_voc['n-Propylbenzene'] == 100) | (lf_voc['n-Propylbenzene'] == 0) , '100 U' , lf_voc['n-Propylbenzene'] )
lf_voc['n-Propylbenzene LF'] = np.where(lf_voc['n-Propylbenzene'] == '100 U' , 10 , lf_voc['n-Propylbenzene'] )

lf_voc['Tetrachloroethylene'] = np.where((lf_voc['Tetrachloroethylene'] == 50) | (lf_voc['Tetrachloroethylene'] == 0) , '50 U' , lf_voc['Tetrachloroethylene'] )
lf_voc['Tetrachloroethylene LF'] = np.where(lf_voc['Tetrachloroethylene'] == '50 U' , 5 , lf_voc['Tetrachloroethylene'] )

lf_voc['Toluene'] = np.where((lf_voc['Toluene'] == 100) | (lf_voc['Toluene'] == 0) , '100 U' , lf_voc['Toluene'] )
lf_voc['Toluene LF'] = np.where(lf_voc['Toluene'] == '100 U' , 10 , lf_voc['Toluene'] )

lf_voc['Trichloroethene'] = np.where((lf_voc['Trichloroethene'] == 50) | (lf_voc['Trichloroethene'] == 0) , '50 U' , lf_voc['Trichloroethene'] )
lf_voc['Trichloroethene LF'] = np.where(lf_voc['Trichloroethene'] == '50 U' , 5 , lf_voc['Trichloroethene'] )

lf_voc['1,2,4-Trimethylbenzene'] = np.where((lf_voc['1,2,4-Trimethylbenzene'] == 100) | (lf_voc['1,2,4-Trimethylbenzene'] == 0) , '100 U' , lf_voc['1,2,4-Trimethylbenzene'] )
lf_voc['1,2,4-Trimethylbenzene LF'] = np.where(lf_voc['1,2,4-Trimethylbenzene'] == '100 U' , 10 , lf_voc['1,2,4-Trimethylbenzene'] )

lf_voc['1,3,5-Trimethylbenzene'] = np.where((lf_voc['1,3,5-Trimethylbenzene'] == 100) | (lf_voc['1,3,5-Trimethylbenzene'] == 0) , '100 U' , lf_voc['1,3,5-Trimethylbenzene'] )
lf_voc['1,3,5-Trimethylbenzene LF'] = np.where(lf_voc['1,3,5-Trimethylbenzene'] == '100 U' , 10 , lf_voc['1,3,5-Trimethylbenzene'] )

lf_voc['Xylenes'] = np.where((lf_voc['Xylenes'] == 150) | (lf_voc['Xylenes'] == 0) , '150 U' , lf_voc['Xylenes'] )
lf_voc['Xylenes LF'] = np.where(lf_voc['Xylenes'] == '150 U' , 15 , lf_voc['Xylenes'] )

lf_voc

Sample ID,Start_Depth,End_Depth,Sample_Date,Benzene,n-Butylbenzene,sec-Butylbenzene,Chlorobenzene,"1,1-Dichloroethane","cis-1,2-Dichloroethene",Ethylbenzene,...,Ethylbenzene LF,Isopropylbenzene LF,Naphthalene LF,n-Propylbenzene LF,Tetrachloroethylene LF,Toluene LF,Trichloroethene LF,"1,2,4-Trimethylbenzene LF","1,3,5-Trimethylbenzene LF",Xylenes LF
TB-N122,1,3,2005-09-22,50 U,50 U,50 U,50 U,50 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TB-N124,8,10,2005-09-28,50 U,50 U,50 U,50 U,50 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TB-N125,5.5,7.5,2005-09-28,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N125.1,13,15,2005-09-28,50 U,50 U,50 U,50 U,50 U,50 U,50 U,...,5,25,370,10,5,10,5,10,10,15
TB-N126,0.5,2.5,2005-09-28,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N126.1,5.5,7.5,2005-09-28,50 U,50 U,50 U,50 U,50 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TB-N127,8,10,2005-09-23,50 U,50 U,50 U,50 U,50 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TB-N128,4,6,2005-09-22,50 U,50 U,50 U,50 U,50 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TB-N129,10.5,12.5,2005-09-23,50 U,50 U,50 U,50 U,50 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TB-N130,0.5,2.5,2005-09-23,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N130.1,10.5,12.5,2005-09-23,55,50 U,50 U,50 U,50 U,210,160,...,160,25,33,10,5,10,140,140,10,600
TB-N131,3,5,2005-09-22,50 U,50 U,50 U,50 U,50 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TB-N132,3,5,2005-09-28,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N132.1,5.5,7.5,2005-09-28,83,160,160,340,290,56,330,...,330,25,33,280,5,10,100,150,10,580

In [29]:
#make the BNA df
BNA_df_1 = table_df.iloc[0:1]
#pg 101 is 24:45
BNA_df_2 = table_df.iloc[22:44]
BNA_df = pd.concat([BNA_df_1,BNA_df_2])
#transpose it
BNA_df = BNA_df.transpose()
#make the first row our column titles
BNA_df.columns=BNA_df.iloc[0]
#drop the duplicate row
BNA_df = BNA_df.tail(-1)
#drop BNA details for mergining
BNA_df = BNA_df.drop('BNA Extraction Date',axis=1)
BNA_df = BNA_df.drop('BNA Analysis Date',axis=1)
BNA_df = BNA_df.drop('BNA Analytical Method',axis=1)
BNA_df = BNA_df.drop(['Sample Depth (ft bgs)'], axis=1)
BNA_df = BNA_df.drop('BNAs',axis=1) # if needed- keep for explanation
#drop samples with no detections
BNA_df = BNA_df.dropna(thresh=3)


#pull sample id out of index
BNA_df['Sample ID'] = BNA_df.index

#shift column sample ID to first position
first_column = BNA_df.pop('Sample ID')
#insert column using insert(position,column_name,first_column) function
BNA_df.insert(0, 'Sample ID', first_column)

#save detections
BNA_df = BNA_df.drop_duplicates(subset=['Sample ID'], keep="first")

#drop sample ID since its in index
BNA_df = BNA_df.drop(['Sample ID'], axis=1)

BNA_df

Sample ID,Anthracene,Benzo(a)anthracene,Benzo(b)fluoranthene,Benzo(a)pyrene,"Benzo(g,h,i)perylene",Benzo(k)fluoranthene,Carbazole,Chrysene,2-Cloronaphthalene,Di-n-octyl phthalate,Fluoranthene,"Indeno(1,2,3-cd)pyrene",2-Methylnaphthalene,Bis(2-ethylhexyl)phthalate,Phenol,Di-n-butyl phthalate,Phenanthrene,Pyrene
TB-N122,NaN,500,410,370,NaN,NaN,NaN,440,NaN,NaN,800,NaN,NaN,NaN,NaN,NaN,420,820
TB-N124,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TB-N125,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N125.1,2600,5300,5000,5100,2400,NaN,NaN,5800,NaN,NaN,8700,NaN,NaN,NaN,NaN,NaN,6300,8300
TB-N126,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N126.1,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TB-N127,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330
TB-N128,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330
TB-N129,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TB-N130,NaN,NaN,2000,NaN,NaN,NaN,NaN,1800,NaN,NaN,4100,NaN,NaN,NaN,NaN,NaN,2600,3200
TB-N130.1,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330
TB-N131,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330
TB-N132,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N132.1,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700

In [22]:
#make the leapfrog inputs for BNA
lf_BNA = BNA_df.transpose()
#replace nan w zero
lf_BNA = lf_BNA.replace(np.nan,0)

#turn zeros into nondetections
# # #fix column TB-N122, 125.1, N130
lf_BNA['TB-N122'] = np.where(lf_BNA['TB-N122']>0, lf_BNA['TB-N122'],'330 U')
lf_BNA['TB-N125.1'] = np.where(lf_BNA['TB-N125.1']>0, lf_BNA['TB-N125.1'],'1700 U')
lf_BNA['TB-N130'] = np.where(lf_BNA['TB-N130']>0, lf_BNA['TB-N130'],'330 U')


# #add U to the rest of the columns for non-detects
lf_BNA['TB-N124'] = np.where(lf_BNA['TB-N124']!=1700, lf_BNA['TB-N124'],'1700 U')
lf_BNA['TB-N126.1'] = np.where(lf_BNA['TB-N126.1']!=1700, lf_BNA['TB-N126.1'],'1700 U')
lf_BNA['TB-N127'] = np.where(lf_BNA['TB-N127']!=330, lf_BNA['TB-N127'],'330 U')
lf_BNA['TB-N128'] = np.where(lf_BNA['TB-N128']!=330, lf_BNA['TB-N128'],'330 U')
lf_BNA['TB-N129'] = np.where(lf_BNA['TB-N129']!=1700, lf_BNA['TB-N129'],'1700 U')
lf_BNA['TB-N130.1'] = np.where(lf_BNA['TB-N130.1']!=330, lf_BNA['TB-N130.1'],'330 U')
lf_BNA['TB-N131'] = np.where(lf_BNA['TB-N131']!=330, lf_BNA['TB-N131'],'330 U')
lf_BNA['TB-N132.1'] = np.where(lf_BNA['TB-N132.1']!=1700, lf_BNA['TB-N132.1'],'1700 U')

#flip for merging
lf_BNA = lf_BNA.transpose()

#add lf values for BNAs
#added for this dataset
lf_BNA['Anthracene LF'] = np.where(lf_BNA['Anthracene']=='1700 U', 170 ,lf_BNA['Anthracene'])
lf_BNA['Anthracene LF'] = np.where(lf_BNA['Anthracene LF']=='330 U', 33 ,lf_BNA['Anthracene LF'])

lf_BNA['Benzo(a)anthracene LF'] = np.where(lf_BNA['Benzo(a)anthracene']=='1700 U', 170 ,lf_BNA['Benzo(a)anthracene'])
lf_BNA['Benzo(a)anthracene LF'] = np.where(lf_BNA['Benzo(a)anthracene LF']=='330 U', 33 ,lf_BNA['Benzo(a)anthracene LF'])

lf_BNA['Benzo(b)fluoranthene LF'] = np.where(lf_BNA['Benzo(b)fluoranthene']=='1700 U', 170 ,lf_BNA['Benzo(b)fluoranthene'])
lf_BNA['Benzo(b)fluoranthene LF'] = np.where(lf_BNA['Benzo(b)fluoranthene LF']=='330 U', 33 ,lf_BNA['Benzo(b)fluoranthene LF'])

lf_BNA['Benzo(g,h,i)perylene LF'] = np.where(lf_BNA['Benzo(g,h,i)perylene']=='1700 U', 170 ,lf_BNA['Benzo(g,h,i)perylene'])
lf_BNA['Benzo(g,h,i)perylene LF'] = np.where(lf_BNA['Benzo(g,h,i)perylene LF']=='330 U', 33 ,lf_BNA['Benzo(g,h,i)perylene LF'])

lf_BNA['Benzo(a)pyrene LF'] = np.where(lf_BNA['Benzo(a)pyrene']=='1700 U', 170 ,lf_BNA['Benzo(a)pyrene'])
lf_BNA['Benzo(a)pyrene LF'] = np.where(lf_BNA['Benzo(a)pyrene LF']=='330 U', 33 ,lf_BNA['Benzo(a)pyrene LF'])

lf_BNA['Benzo(k)fluoranthene LF'] = np.where(lf_BNA['Benzo(k)fluoranthene']=='1700 U', 170 ,lf_BNA['Benzo(k)fluoranthene'])
lf_BNA['Benzo(k)fluoranthene LF'] = np.where(lf_BNA['Benzo(k)fluoranthene LF']=='330 U', 33 ,lf_BNA['Benzo(k)fluoranthene LF'])

#added for this dataset
lf_BNA['Carbazole LF'] = np.where(lf_BNA['Carbazole']=='1700 U', 170 ,lf_BNA['Carbazole'])
lf_BNA['Carbazole LF'] = np.where(lf_BNA['Carbazole LF']=='330 U', 33 ,lf_BNA['Carbazole LF'])

lf_BNA['Chrysene LF'] = np.where(lf_BNA['Chrysene']=='1700 U', 170 ,lf_BNA['Chrysene'])
lf_BNA['Chrysene LF'] = np.where(lf_BNA['Chrysene LF']=='330 U', 33 ,lf_BNA['Chrysene LF'])

lf_BNA['2-Cloronaphthalene LF'] = np.where(lf_BNA['2-Cloronaphthalene']=='1700 U', 170 ,lf_BNA['2-Cloronaphthalene'])
lf_BNA['2-Cloronaphthalene LF'] = np.where(lf_BNA['2-Cloronaphthalene LF']=='330 U', 33 ,lf_BNA['2-Cloronaphthalene LF'])

#not in this dataset
# lf_BNA['2,4-Dimethylphenol LF'] = np.where(lf_BNA['2,4-Dimethylphenol']=='1700 U', 170 ,lf_BNA['2,4-Dimethylphenol'])
# lf_BNA['2,4-Dimethylphenol LF'] = np.where(lf_BNA['2,4-Dimethylphenol']=='330 U', 33 ,lf_BNA['2,4-Dimethylphenol'])

lf_BNA['Di-n-octyl phthalate LF'] = np.where(lf_BNA['Di-n-octyl phthalate']=='1700 U', 170 ,lf_BNA['Di-n-octyl phthalate'])
lf_BNA['Di-n-octyl phthalate LF'] = np.where(lf_BNA['Di-n-octyl phthalate LF']=='330 U', 33 ,lf_BNA['Di-n-octyl phthalate LF'])

lf_BNA['Fluoranthene LF'] = np.where(lf_BNA['Fluoranthene']=='1700 U', 170 ,lf_BNA['Fluoranthene'])
lf_BNA['Fluoranthene LF'] = np.where(lf_BNA['Fluoranthene LF']=='330 U', 33 ,lf_BNA['Fluoranthene LF'])

lf_BNA['Indeno(1,2,3-cd)pyrene LF'] = np.where(lf_BNA['Indeno(1,2,3-cd)pyrene']=='1700 U', 170 ,lf_BNA['Indeno(1,2,3-cd)pyrene'])
lf_BNA['Indeno(1,2,3-cd)pyrene LF'] = np.where(lf_BNA['Indeno(1,2,3-cd)pyrene LF']=='330 U', 33 ,lf_BNA['Indeno(1,2,3-cd)pyrene LF'])

lf_BNA['2-Methylnaphthalene LF'] = np.where(lf_BNA['2-Methylnaphthalene']=='1700 U', 170 ,lf_BNA['2-Methylnaphthalene'])
lf_BNA['2-Methylnaphthalene LF'] = np.where(lf_BNA['2-Methylnaphthalene LF']=='330 U', 33 ,lf_BNA['2-Methylnaphthalene LF'])

lf_BNA['Bis(2-ethylhexyl)phthalate LF'] = np.where(lf_BNA['Bis(2-ethylhexyl)phthalate']=='1700 U', 170 ,lf_BNA['Bis(2-ethylhexyl)phthalate'])
lf_BNA['Bis(2-ethylhexyl)phthalate LF'] = np.where(lf_BNA['Bis(2-ethylhexyl)phthalate LF']=='330 U', 33 ,lf_BNA['Bis(2-ethylhexyl)phthalate LF'])

lf_BNA['Phenol LF'] = np.where(lf_BNA['Phenol']=='1700 U', 170 ,lf_BNA['Phenol'])
lf_BNA['Phenol LF'] = np.where(lf_BNA['Phenol LF']=='330 U', 33 ,lf_BNA['Phenol LF'])

lf_BNA['Di-n-butyl phthalate LF'] = np.where(lf_BNA['Di-n-butyl phthalate']=='1700 U', 170 ,lf_BNA['Di-n-butyl phthalate'])
lf_BNA['Di-n-butyl phthalate LF'] = np.where(lf_BNA['Di-n-butyl phthalate LF']=='330 U', 33 ,lf_BNA['Di-n-butyl phthalate LF'])

lf_BNA['Phenanthrene LF'] = np.where(lf_BNA['Phenanthrene']=='1700 U', 170 ,lf_BNA['Phenanthrene'])
lf_BNA['Phenanthrene LF'] = np.where(lf_BNA['Phenanthrene LF']=='330 U', 33 ,lf_BNA['Phenanthrene LF'])

lf_BNA['Pyrene LF'] = np.where(lf_BNA['Pyrene']=='1700 U', 170 ,lf_BNA['Pyrene'])
lf_BNA['Pyrene LF'] = np.where(lf_BNA['Pyrene LF']=='330 U', 33 ,lf_BNA['Pyrene LF'])

lf_BNA

Sample ID,Anthracene,Benzo(a)anthracene,Benzo(b)fluoranthene,Benzo(a)pyrene,"Benzo(g,h,i)perylene",Benzo(k)fluoranthene,Carbazole,Chrysene,2-Cloronaphthalene,Di-n-octyl phthalate,...,2-Cloronaphthalene LF,Di-n-octyl phthalate LF,Fluoranthene LF,"Indeno(1,2,3-cd)pyrene LF",2-Methylnaphthalene LF,Bis(2-ethylhexyl)phthalate LF,Phenol LF,Di-n-butyl phthalate LF,Phenanthrene LF,Pyrene LF
TB-N122,330 U,500,410,370,330 U,330 U,330 U,440,330 U,330 U,...,33,33,800,33,33,33,33,33,420,820
TB-N124,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TB-N125,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N125.1,2600,5300,5000,5100,2400,1700 U,1700 U,5800,1700 U,1700 U,...,170,170,8700,170,170,170,170,170,6300,8300
TB-N126,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N126.1,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TB-N127,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,...,33,33,33,33,33,33,33,33,33,33
TB-N128,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,...,33,33,33,33,33,33,33,33,33,33
TB-N129,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TB-N130,330 U,330 U,2000,330 U,330 U,330 U,330 U,1800,330 U,330 U,...,33,33,4100,33,33,33,33,33,2600,3200
TB-N130.1,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,...,33,33,33,33,33,33,33,33,33,33
TB-N131,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,...,33,33,33,33,33,33,33,33,33,33
TB-N132,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N132.1,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170

In [23]:
#make the metals df
metals_df_1 = table_df.iloc[0:1]
metals_df_2 = table_df.iloc[44:60]
metals_df = pd.concat([metals_df_1,metals_df_2])
# #transpose it
metals_df = metals_df.transpose()
# #make the first row our column titles
metals_df.columns=metals_df.iloc[0]
# #drop the duplicate row
metals_df = metals_df.tail(-1)
#drop metals details for merging
metals_df = metals_df.drop('Metals Analysis Date',axis=1) 
metals_df = metals_df.drop('Analytical Method',axis=1)
metals_df = metals_df.drop('Metals',axis=1) #- keep for explanation
# #drop samples with no detections
metals_df = metals_df.dropna(thresh=2)

#pull sample id out of index
metals_df['Sample ID'] = metals_df.index
#shift column sample ID to first position
first_column = metals_df.pop('Sample ID')
#insert column using insert(position,column_name,first_column) function
metals_df.insert(0, 'Sample ID', first_column)

#drop samples with no detections
metals_df = metals_df.drop_duplicates(subset=['Sample ID'], keep="first")

#drop informational columns for merging
metals_df = metals_df.drop(['Sample ID'], axis=1)
metals_df = metals_df.drop(['Sample Depth (ft bgs)'], axis=1)

############################################
metals_df

Sample ID,Arsenic,Barium,Cadmium,Chromium,Chromium IV,"Lead, total (calculated)","Lead, fine fraction","Lead, coarse fraction",Manganese,Mercury,Nickel,Vanadium,Zinc
TB-N122,2400,28000,200,56000,NaN,12000,18600,7520,970000,300,10000,14000,31000
TB-N124,1900,15000,100,5600,NaN,9080,21900,2060,170000,NaN,4800,5100,13000
TB-N125,13000,110000,2900,240000,NaN,211000,295000,188000,1200000,490,120000,22000,370000
TB-N125.1,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N126,1700,480000,180,18000,NaN,23900,37500,16400,4900000,NaN,6500,9800,21000
TB-N126.1,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N127,1200,13000,NaN,8600,NaN,5150,6420,3810,73000,NaN,6200,4400,12000
TB-N128,440,190000,NaN,32000,NaN,3530,14500,2390,2000000,NaN,1700,18000,14000
TB-N129,3400,51000,2500,87000,NaN,78400,116000,74100,1300000,56,48000,19000,110000
TB-N130,5200,200000,1100,88000,NaN,156000,226000,140000,3900000,3500,13000,40000,310000
TB-N130.1,6500,290000,2100,83000,NaN,262000,340000,249000,1100000,390,89000,12000,400000
TB-N131,6300,52000,190,62000,NaN,22400,37100,12700,1900000,NaN,9400,36000,100000
TB-N132,12000,160000,4400,130000,NaN,659000,637000,669000,4100000,3400,54000,30000,2700000
TB-N132.1,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT

In [24]:
#make the leapfrog inputs for metals
lf_metals = metals_df
#replace nan w zero
lf_metals = lf_metals.replace(np.nan,0)

#isolate the results
lf_metals = lf_metals.iloc[0:]

#fix mercury non detect
lf_metals['Mercury'] = np.where(lf_metals['Mercury']==0, f'50' + ' U' , lf_metals['Mercury'])
#add mercury LF column
lf_metals['Mercury LF'] = np.where(lf_metals['Mercury']=='50 U', 5 , lf_metals['Mercury'])
# fix Chromium IV nondetect
lf_metals['Chromium IV'] = np.where(lf_metals['Chromium IV']==0, f'500' + ' U' , lf_metals['Chromium IV'])
#add mercury LF column
lf_metals['Chromium IV LF'] = np.where(lf_metals['Chromium IV']=='500 U', 50 , lf_metals['Chromium IV'])

lf_metals

Sample ID,Arsenic,Barium,Cadmium,Chromium,Chromium IV,"Lead, total (calculated)","Lead, fine fraction","Lead, coarse fraction",Manganese,Mercury,Nickel,Vanadium,Zinc,Mercury LF,Chromium IV LF
TB-N122,2400,28000,200,56000,500 U,12000,18600,7520,970000,300,10000,14000,31000,300,50
TB-N124,1900,15000,100,5600,500 U,9080,21900,2060,170000,50 U,4800,5100,13000,5,50
TB-N125,13000,110000,2900,240000,500 U,211000,295000,188000,1200000,490,120000,22000,370000,490,50
TB-N125.1,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N126,1700,480000,180,18000,500 U,23900,37500,16400,4900000,50 U,6500,9800,21000,5,50
TB-N126.1,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N127,1200,13000,0,8600,500 U,5150,6420,3810,73000,50 U,6200,4400,12000,5,50
TB-N128,440,190000,0,32000,500 U,3530,14500,2390,2000000,50 U,1700,18000,14000,5,50
TB-N129,3400,51000,2500,87000,500 U,78400,116000,74100,1300000,56,48000,19000,110000,56,50
TB-N130,5200,200000,1100,88000,500 U,156000,226000,140000,3900000,3500,13000,40000,310000,3500,50
TB-N130.1,6500,290000,2100,83000,500 U,262000,340000,249000,1100000,390,89000,12000,400000,390,50
TB-N131,6300,52000,190,62000,500 U,22400,37100,12700,1900000,50 U,9400,36000,100000,5,50
TB-N132,12000,160000,4400,130000,500 U,659000,637000,669000,4100000,3400,54000,30000,2700000,3400,50
TB-N132.1,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT

In [25]:
#make the PCBs df
PCB_df_1 = table_df.iloc[0:1]
PCB_df_2 = table_df.iloc[60:65]
PCB_df = pd.concat([PCB_df_1,PCB_df_2])
# #transpose it
PCB_df = PCB_df.transpose()
#make the first row our column titles
PCB_df.columns=PCB_df.iloc[0]
#drop the duplicate row
PCB_df = PCB_df.tail(-1)
#drop extra info
PCB_df = PCB_df.drop('PCB Extraction Date',axis=1)
PCB_df = PCB_df.drop('PCB Analysis Date',axis=1)
PCB_df = PCB_df.drop('PCB Analytical Method',axis=1)
PCB_df = PCB_df.drop('PCBs',axis=1)
#drop samples with no detections
PCB_df = PCB_df.dropna(thresh=2)
#indicate the nondetects
PCB_df = PCB_df.replace(np.nan,'330 U')

#pull sample id out of index
PCB_df['Sample ID'] = PCB_df.index
#shift column sample ID to first position
first_column = PCB_df.pop('Sample ID')
#insert column using insert(position,column_name,first_column) function
PCB_df.insert(0, 'Sample ID', first_column)

#drop duplicate rows
PCB_df = PCB_df.drop_duplicates(subset=['Sample ID'], keep="first")

#drop extra info
PCB_df = PCB_df.drop(['Sample Depth (ft bgs)'], axis=1)
PCB_df = PCB_df.drop(['Sample ID'], axis=1)

PCB_df

Sample ID Aroclors
TB-N122         NT
TB-N124         NT
TB-N125         NT
TB-N125.1       NT
TB-N126         NT
TB-N126.1       NT
TB-N127         NT
TB-N128        330
TB-N129         NT
TB-N130        330
TB-N130.1      330
TB-N131         NT
TB-N132         NT
TB-N132.1       NT

In [26]:
#make the leapfrog inputs for PCBs
lf_PCB = PCB_df

#modify existing columns for leapfrog
#only general Aroclors for this data
lf_PCB['Aroclors'] = np.where(lf_PCB['Aroclors'] == 330 , '330 U' ,lf_PCB['Aroclors'])
#lf_PCB['Aroclor-1254'] = np.where(lf_PCB['Aroclor-1254'] == 330 , '330 U' ,lf_PCB['Aroclor-1254'])
#lf_PCB['Aroclor-1260'] = np.where(lf_PCB['Aroclor-1260'] == 330, '330 U' ,lf_PCB['Aroclor-1260'])

#add leapfrog input for PCBs
lf_PCB['Aroclors LF'] = np.where(lf_PCB['Aroclors'] == '330 U' , 3.3 ,lf_PCB['Aroclors'])
# lf_PCB['Aroclor-1254 LF'] = np.where(lf_PCB['Aroclor-1254'] == '330 U', 3.3 ,lf_PCB['Aroclor-1254'])
# lf_PCB['Aroclor-1260 LF'] = np.where(lf_PCB['Aroclor-1260'] == '330 U', 3.3 ,lf_PCB['Aroclor-1260'])

lf_PCB

Sample ID Aroclors Aroclors LF
TB-N122         NT          NT
TB-N124         NT          NT
TB-N125         NT          NT
TB-N125.1       NT          NT
TB-N126         NT          NT
TB-N126.1       NT          NT
TB-N127         NT          NT
TB-N128      330 U         3.3
TB-N129         NT          NT
TB-N130      330 U         3.3
TB-N130.1    330 U         3.3
TB-N131         NT          NT
TB-N132         NT          NT
TB-N132.1       NT          NT

In [27]:
#merge tables
combined_lf= pd.merge(lf_BNA,lf_metals, left_index = True, right_index = True)
combined_lf= pd.merge(combined_lf,lf_PCB, left_index = True, right_index = True)
combined_lf= pd.merge(combined_lf,lf_voc, left_index = True, right_index = True)

#shift depths and date to front of df 
first_column = combined_lf.pop('Start_Depth')
second_column = combined_lf.pop('End_Depth')
third_column = combined_lf.pop('Sample_Date')

#sort columns alphabetically
combined_lf = combined_lf.sort_index(axis = 1, ascending = True)
  
#insert column using insert(position,column_name,first_column) function
combined_lf.insert(0, 'Start_Depth', first_column)
combined_lf.insert(1, 'End_Depth', second_column)
combined_lf.insert(2, 'Sample_Date', third_column)

#setindex name
combined_lf.index.name='Sample_ID'

combined_lf

Sample ID,Start_Depth,End_Depth,Sample_Date,"1,1-Dichloroethane","1,1-Dichloroethane LF","1,2,4-Trimethylbenzene","1,2,4-Trimethylbenzene LF","1,3,5-Trimethylbenzene","1,3,5-Trimethylbenzene LF",2-Cloronaphthalene,...,Xylenes LF,Zinc,"cis-1,2-Dichloroethene","cis-1,2-Dichloroethene LF",n-Butylbenzene,n-Butylbenzene LF,n-Propylbenzene,n-Propylbenzene LF,sec-Butylbenzene,sec-Butylbenzene LF
Sample_ID,,,,,,,,,,,,,,,,,,,,,
TB-N122,1,3,2005-09-22,50 U,5,100 U,10,100 U,10,330 U,...,15,31000,50 U,5,50 U,5,100 U,10,50 U,5
TB-N124,8,10,2005-09-28,50 U,5,100 U,10,100 U,10,1700 U,...,15,13000,50 U,5,50 U,5,100 U,10,50 U,5
TB-N125,5.5,7.5,2005-09-28,NT,NT,NT,NT,NT,NT,NT,...,NT,370000,NT,NT,NT,NT,NT,NT,NT,NT
TB-N125.1,13,15,2005-09-28,50 U,5,100 U,10,100 U,10,1700 U,...,15,NT,50 U,5,50 U,5,100 U,10,50 U,5
TB-N126,0.5,2.5,2005-09-28,NT,NT,NT,NT,NT,NT,NT,...,NT,21000,NT,NT,NT,NT,NT,NT,NT,NT
TB-N126.1,5.5,7.5,2005-09-28,50 U,5,100 U,10,100 U,10,1700 U,...,15,NT,50 U,5,50 U,5,100 U,10,50 U,5
TB-N127,8,10,2005-09-23,50 U,5,100 U,10,100 U,10,330 U,...,15,12000,50 U,5,50 U,5,100 U,10,50 U,5
TB-N128,4,6,2005-09-22,50 U,5,100 U,10,100 U,10,330 U,...,15,14000,50 U,5,50 U,5,100 U,10,50 U,5
TB-N129,10.5,12.5,2005-09-23,50 U,5,100 U,10,100 U,10,1700 U,...,15,110000,50 U,5,50 U,5,100 U,10,50 U,5
TB-N130,0.5,2.5,2005-09-23,NT,NT,NT,NT,NT,NT,330 U,...,NT,310000,NT,NT,NT,NT,NT,NT,NT,NT
TB-N130.1,10.5,12.5,2005-09-23,50 U,5,140,140,100 U,10,330 U,...,600,400000,210,210,50 U,5,100 U,10,50 U,5
TB-N131,3,5,2005-09-22,50 U,5,100 U,10,100 U,10,330 U,...,15,100000,50 U,5,50 U,5,100 U,10,50 U,5
TB-N132,3,5,2005-09-28,NT,NT,NT,NT,NT,NT,NT,...,NT,2700000,NT,NT,NT,NT,NT,NT,NT,NT
TB-N132.1,5.5,7.5,2005-09-28,290,290,150,150,100 U,10,1700 U,...,580,NT,56,56,160,160,280,280,160,160

In [28]:
combined_lf.to_csv('LeapFrog Exports/Pg96.csv')