In [1]:
import pandas as pd
import numpy as np

In [2]:
table = "NTH Soil data 2005_PF.xlsx"

In [3]:
#run this across each sheet of the file
table_df = pd.read_excel(table, sheet_name = 2)
table_df

,Sample ID,TB-N133,Unnamed: 2,Unnamed: 3,TB-N134,Unnamed: 5,Unnamed: 6,TB-N135,Unnamed: 8,Unnamed: 9,...,Unnamed: 33,TB-N142,Unnamed: 35,Unnamed: 36,TB-N143,Unnamed: 38,Unnamed: 39,TB-N144,Unnamed: 41,Unnamed: 42
0,Sample Depth (ft bgs),5.5-6,NaN,NaN,5.5-7.5,NaN,NaN,5.5-7.5,NaN,NaN,...,NaN,8-10,NaN,NaN,8-10,NaN,NaN,0.5-2.5,NaN,NaN
1,Collection Date,2005-09-27 00:00:00,NaN,NaN,2005-09-27 00:00:00,NaN,NaN,2005-09-24 00:00:00,NaN,NaN,...,NaN,2005-09-28 00:00:00,NaN,NaN,2005-09-28 00:00:00,NaN,NaN,2005-09-28 00:00:00,NaN,NaN
2,VOC Analysis Date,2005-10-06 00:00:00,NaN,NaN,2005-10-04 00:00:00,NaN,NaN,2005-09-30 00:00:00,NaN,NaN,...,NaN,2005-10-06 00:00:00,NaN,NaN,2005-10-06 00:00:00,NaN,NaN,NT,NaN,NaN
3,VOC Extraction Date,2005-09-27 00:00:00,NaN,NaN,2005-09-29 00:00:00,NaN,NaN,2005-09-24 00:00:00,NaN,NaN,...,NaN,2005-09-28 00:00:00,NaN,NaN,2005-09-28 00:00:00,NaN,NaN,NT,NaN,NaN
4,VOC Analytical Method,SW846 8260B,NaN,NaN,SW846 8260B,NaN,NaN,SW846 8260B,NaN,NaN,...,NaN,SW846 8260B,NaN,NaN,SW846 8260B,NaN,NaN,NT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,NT = not tested,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,PCB = polychlorinated biphenyl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,TB = test boring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,Âµg/kg = microgram per kilogram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,VOC = volatile organic compound,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#replace - with NA for dropping purposes
table_df = table_df.replace('â',np.nan)

#fix the unnamed columns

for i in list(range(1,len(table_df.columns),3)):
    
    #rename columns
    newCol1 = str(table_df.columns.tolist()[i])
    newCol2 = str(table_df.columns.tolist()[i])
    table_df.iat[0,i+1]  = table_df.iat[0,i]
    table_df.iat[0,i+2]  = table_df.iat[0,i]
    table_df.iat[1,i+1]  = table_df.iat[1,i]
    table_df.iat[1,i+2]  = table_df.iat[1,i]
    table_df.iat[2,i+1]  = table_df.iat[2,i]
    table_df.iat[2,i+2]  = table_df.iat[2,i]
    table_df.iat[3,i+1]  = table_df.iat[3,i]
    table_df.iat[3,i+2]  = table_df.iat[3,i]
    table_df = table_df.rename(columns = {table_df.columns.to_list()[i+1]:newCol1})
    table_df = table_df.rename(columns = {table_df.columns.to_list()[i+2]:newCol2})
   # print(i)
table_df

,Sample ID,TB-N133,TB-N133,TB-N133,TB-N134,TB-N134,TB-N134,TB-N135,TB-N135,TB-N135,...,TB-N141,TB-N142,TB-N142,TB-N142,TB-N143,TB-N143,TB-N143,TB-N144,TB-N144,TB-N144
0,Sample Depth (ft bgs),5.5-6,5.5-6,5.5-6,5.5-7.5,5.5-7.5,5.5-7.5,5.5-7.5,5.5-7.5,5.5-7.5,...,13-15,8-10,8-10,8-10,8-10,8-10,8-10,0.5-2.5,0.5-2.5,0.5-2.5
1,Collection Date,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-24 00:00:00,2005-09-24 00:00:00,2005-09-24 00:00:00,...,2005-09-24 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00
2,VOC Analysis Date,2005-10-06 00:00:00,2005-10-06 00:00:00,2005-10-06 00:00:00,2005-10-04 00:00:00,2005-10-04 00:00:00,2005-10-04 00:00:00,2005-09-30 00:00:00,2005-09-30 00:00:00,2005-09-30 00:00:00,...,2005-09-30 00:00:00,2005-10-06 00:00:00,2005-10-06 00:00:00,2005-10-06 00:00:00,2005-10-06 00:00:00,2005-10-06 00:00:00,2005-10-06 00:00:00,NT,NT,NT
3,VOC Extraction Date,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-27 00:00:00,2005-09-29 00:00:00,2005-09-29 00:00:00,2005-09-29 00:00:00,2005-09-24 00:00:00,2005-09-24 00:00:00,2005-09-24 00:00:00,...,2005-09-24 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,2005-09-28 00:00:00,NT,NT,NT
4,VOC Analytical Method,SW846 8260B,NaN,NaN,SW846 8260B,NaN,NaN,SW846 8260B,NaN,NaN,...,NaN,SW846 8260B,NaN,NaN,SW846 8260B,NaN,NaN,NT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,NT = not tested,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,PCB = polychlorinated biphenyl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,TB = test boring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,Âµg/kg = microgram per kilogram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,VOC = volatile organic compound,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
#isolate VOC data
voc_df = table_df.iloc[:22]

##################################################
#transpose it
voc_df = voc_df.transpose()
#make the first row our column titles
voc_df.columns=voc_df.iloc[0]
#drop the duplicate row
voc_df = voc_df.tail(-1)
#drop samples with no detections
voc_df = voc_df.dropna(thresh=7)
##################################################

voc_df.index.name = None

# ###########################################

# #drop VOC details for mergining
voc_df = voc_df.drop('VOC Analysis Date',axis=1)
voc_df = voc_df.drop('VOC Analytical Method',axis=1)
voc_df = voc_df.drop('VOC Extraction Date',axis=1)
voc_df = voc_df.drop('VOCs',axis=1) # bring back for explanation if necessary

#pull sample id out of index
voc_df['Sample ID'] = voc_df.index

#shift column sample ID to first position
first_column = voc_df.pop('Sample ID')
#insert column using insert(position,column_name,first_column) function
voc_df.insert(0, 'Sample ID', first_column)




#drop duplicates and keep the first appearance because those are the detections / tests
voc_df = voc_df.drop_duplicates(subset=['Sample ID'],keep="first")

#split sample depth range into two separate columns
voc_df[['Start_Depth','End_Depth']] = voc_df.get('Sample Depth (ft bgs)').str.split("-",expand=True)

#shift depths to front of df 
first_column = voc_df.pop('Start_Depth')
second_column = voc_df.pop('End_Depth')
  
# insert column using insert(position,column_name,
# first_column) function
voc_df.insert(1, 'Start_Depth', first_column)
voc_df.insert(2, 'End_Depth', second_column)

#drop sample ID and depth range
voc_df = voc_df.drop(['Sample ID'], axis=1)
voc_df = voc_df.drop(['Sample Depth (ft bgs)'], axis=1)

#rename voc columns
voc_df = voc_df.rename(columns = {'Collection Date':'Sample_Date'})

voc_df
#change format of date to eliminate the time?

Sample ID,Start_Depth,End_Depth,Sample_Date,Benzene,n-Butylbenzene,sec-Butylbenzene,Chlorobenzene,"1,1-Dichloroethane","cis-1,2-Dichloroethene",Ethylbenzene,Isopropylbenzene,Naphthalene,n-Propylbenzene,Tetrachloroethylene,Toluene,Trichloroethene,"1,2,4-Trimethylbenzene","1,3,5-Trimethylbenzene",Xylenes
TB-N133,5.5,6,2005-09-27 00:00:00,NaN,560,280,NaN,NaN,NaN,330,NaN,2000,360,NaN,660,NaN,3500,1100,2200
TB-N134,5.5,7.5,2005-09-27 00:00:00,50,50,50,50,50,50,50,250,330,100,50,100,50,100,100,150
TB-N135,5.5,7.5,2005-09-24 00:00:00,50,50,50,50,50,50,50,250,330,100,50,100,50,100,100,150
TB-N135.1,10.5,12.5,2005-09-24 00:00:00,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N136B,10.5,12.5,2005-09-26 00:00:00,NaN,54,NaN,NaN,NaN,NaN,71,NaN,NaN,NaN,NaN,NaN,90,420,230,770
TB-N137,10.5,12.5,2005-09-26 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,340,NaN,NaN,NaN,NaN,200,NaN,180
TB-N138,2.5,5.0,2005-09-27 00:00:00,50,50,50,50,50,50,50,250,330,100,50,100,50,100,100,150
TB-N139,3,4,2005-09-29 00:00:00,50,50,50,50,50,50,50,250,330,100,50,100,50,100,100,150
TB-N140,0.5,2.5,2005-09-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,60,NaN,NaN,NaN,380,750,NaN,260,200,240
TB-N140.1,8,10,2005-09-29 00:00:00,NaN,NaN,NaN,NaN,NaN,150,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TB-N141,13,15,2005-09-24 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150,NaN,NaN
TB-N142,8,10,2005-09-28 00:00:00,50,50,50,50,50,50,50,250,330,100,50,100,50,100,100,150
TB-N143,8,10,2005-09-28 00:00:00,NaN,NaN,NaN,NaN,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TB-N144,0.5,2.5,2005-09-28 00:00:00,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT

In [13]:
#adjust voc_df for leapfrog input
#reformatting the original combined df
lf_voc = voc_df.replace(np.nan,0)

#vocs

lf_voc['Benzene '] = np.where((lf_voc['Benzene '] == 50) |(lf_voc['Benzene '] == 0) , '50 U' , lf_voc['Benzene '] )
lf_voc['Benzene LF'] = np.where(lf_voc['Benzene '] == '50 U' , 5 , lf_voc['Benzene '] )

lf_voc['n-Butylbenzene'] = np.where((lf_voc['n-Butylbenzene'] == 50) |(lf_voc['n-Butylbenzene'] == 0) , '50 U' , lf_voc['n-Butylbenzene'] )
lf_voc['n-Butylbenzene LF'] = np.where(lf_voc['n-Butylbenzene'] == '50 U' , 5 , lf_voc['n-Butylbenzene'] )

lf_voc['sec-Butylbenzene'] = np.where((lf_voc['sec-Butylbenzene'] == 50) |(lf_voc['sec-Butylbenzene'] == 0) , '50 U' , lf_voc['sec-Butylbenzene'] )
lf_voc['sec-Butylbenzene LF'] = np.where(lf_voc['sec-Butylbenzene'] == '50 U' , 5 , lf_voc['sec-Butylbenzene'] )

#not in this data
# lf_voc['Tert-Butylbenzene'] = np.where((lf_voc['tert-Butylbenzene'] == 50) |(lf_voc['tert-Butylbenzene'] == 0) , '50 U' , lf_voc['tert-Butylbenzene'] )
# lf_voc['Tert-Butylbenzene LF'] = np.where(lf_voc['tert-Butylbenzene'] == '50 U' , 5 , lf_voc['tert-Butylbenzene'] )

#not in this data
# lf_voc['Carbon Disulfide'] = np.where((lf_voc['Carbon Disulfide'] == 250) |(lf_voc['Carbon Disulfide'] == 0) , '250 U' , lf_voc['Carbon Disulfide'] )
# lf_voc['Carbon Disulfide LF'] = np.where(lf_voc['Carbon Disulfide'] == '250 U' , 25 , lf_voc['Carbon Disulfide'] )

lf_voc['Chlorobenzene'] = np.where((lf_voc['Chlorobenzene'] == 50) |(lf_voc['Chlorobenzene'] == 0) , '50 U' , lf_voc['Chlorobenzene'] )
lf_voc['Chlorobenzene LF'] = np.where(lf_voc['Chlorobenzene'] == '50 U' , 5 , lf_voc['Chlorobenzene'] )

lf_voc['1,1-Dichloroethane'] = np.where((lf_voc['1,1-Dichloroethane'] == 50) |(lf_voc['1,1-Dichloroethane'] == 0) , '50 U' , lf_voc['1,1-Dichloroethane'] )
lf_voc['1,1-Dichloroethane LF'] = np.where(lf_voc['1,1-Dichloroethane'] == '50 U' , 5 , lf_voc['1,1-Dichloroethane'] )

lf_voc['cis-1,2-Dichloroethene'] = np.where((lf_voc['cis-1,2-Dichloroethene'] == 50) |(lf_voc['cis-1,2-Dichloroethene'] == 0) , '50 U' , lf_voc['cis-1,2-Dichloroethene'] )
lf_voc['cis-1,2-Dichloroethene LF'] = np.where(lf_voc['cis-1,2-Dichloroethene'] == '50 U' , 5 , lf_voc['cis-1,2-Dichloroethene'] )

lf_voc['Ethylbenzene'] = np.where((lf_voc['Ethylbenzene'] == 50) |(lf_voc['Ethylbenzene'] == 0) , '50 U' , lf_voc['Ethylbenzene'] )
lf_voc['Ethylbenzene LF'] = np.where(lf_voc['Ethylbenzene'] == '50 U' , 5 , lf_voc['Ethylbenzene'] )

lf_voc['Isopropylbenzene'] = np.where((lf_voc['Isopropylbenzene'] == 250) | (lf_voc['Isopropylbenzene'] == 0) , '250 U' , lf_voc['Isopropylbenzene'] )
lf_voc['Isopropylbenzene LF'] = np.where(lf_voc['Isopropylbenzene'] == '250 U' , 25 , lf_voc['Isopropylbenzene'] )

lf_voc['Naphthalene'] = np.where((lf_voc['Naphthalene'] == 330) | (lf_voc['Naphthalene'] == 0) , '330 U' , lf_voc['Naphthalene'] )
lf_voc['Naphthalene LF'] = np.where(lf_voc['Naphthalene'] == '330 U' , 33 , lf_voc['Naphthalene'] )

lf_voc['n-Propylbenzene'] = np.where((lf_voc['n-Propylbenzene'] == 100) | (lf_voc['n-Propylbenzene'] == 0) , '100 U' , lf_voc['n-Propylbenzene'] )
lf_voc['n-Propylbenzene LF'] = np.where(lf_voc['n-Propylbenzene'] == '100 U' , 10 , lf_voc['n-Propylbenzene'] )

lf_voc['Tetrachloroethylene'] = np.where((lf_voc['Tetrachloroethylene'] == 50) | (lf_voc['Tetrachloroethylene'] == 0) , '50 U' , lf_voc['Tetrachloroethylene'] )
lf_voc['Tetrachloroethylene LF'] = np.where(lf_voc['Tetrachloroethylene'] == '50 U' , 5 , lf_voc['Tetrachloroethylene'] )

lf_voc['Toluene'] = np.where((lf_voc['Toluene'] == 100) | (lf_voc['Toluene'] == 0) , '100 U' , lf_voc['Toluene'] )
lf_voc['Toluene LF'] = np.where(lf_voc['Toluene'] == '100 U' , 10 , lf_voc['Toluene'] )

lf_voc['Trichloroethene'] = np.where((lf_voc['Trichloroethene'] == 50) | (lf_voc['Trichloroethene'] == 0) , '50 U' , lf_voc['Trichloroethene'] )
lf_voc['Trichloroethene LF'] = np.where(lf_voc['Trichloroethene'] == '50 U' , 5 , lf_voc['Trichloroethene'] )

lf_voc['1,2,4-Trimethylbenzene'] = np.where((lf_voc['1,2,4-Trimethylbenzene'] == 100) | (lf_voc['1,2,4-Trimethylbenzene'] == 0) , '100 U' , lf_voc['1,2,4-Trimethylbenzene'] )
lf_voc['1,2,4-Trimethylbenzene LF'] = np.where(lf_voc['1,2,4-Trimethylbenzene'] == '100 U' , 10 , lf_voc['1,2,4-Trimethylbenzene'] )

lf_voc['1,3,5-Trimethylbenzene'] = np.where((lf_voc['1,3,5-Trimethylbenzene'] == 100) | (lf_voc['1,3,5-Trimethylbenzene'] == 0) , '100 U' , lf_voc['1,3,5-Trimethylbenzene'] )
lf_voc['1,3,5-Trimethylbenzene LF'] = np.where(lf_voc['1,3,5-Trimethylbenzene'] == '100 U' , 10 , lf_voc['1,3,5-Trimethylbenzene'] )

lf_voc['Xylenes'] = np.where((lf_voc['Xylenes'] == 150) | (lf_voc['Xylenes'] == 0) , '150 U' , lf_voc['Xylenes'] )
lf_voc['Xylenes LF'] = np.where(lf_voc['Xylenes'] == '150 U' , 15 , lf_voc['Xylenes'] )

lf_voc

Sample ID,Start_Depth,End_Depth,Sample_Date,Benzene,n-Butylbenzene,sec-Butylbenzene,Chlorobenzene,"1,1-Dichloroethane","cis-1,2-Dichloroethene",Ethylbenzene,...,Ethylbenzene LF,Isopropylbenzene LF,Naphthalene LF,n-Propylbenzene LF,Tetrachloroethylene LF,Toluene LF,Trichloroethene LF,"1,2,4-Trimethylbenzene LF","1,3,5-Trimethylbenzene LF",Xylenes LF
TB-N133,5.5,6,2005-09-27,50 U,560,280,50 U,50 U,50 U,330,...,330,25,2000,360,5,660,5,3500,1100,2200
TB-N134,5.5,7.5,2005-09-27,50 U,50 U,50 U,50 U,50 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TB-N135,5.5,7.5,2005-09-24,50 U,50 U,50 U,50 U,50 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TB-N135.1,10.5,12.5,2005-09-24,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N136B,10.5,12.5,2005-09-26,50 U,54,50 U,50 U,50 U,50 U,71,...,71,25,33,10,5,10,90,420,230,770
TB-N137,10.5,12.5,2005-09-26,50 U,50 U,50 U,50 U,50 U,50 U,50 U,...,5,25,340,10,5,10,5,200,10,180
TB-N138,2.5,5.0,2005-09-27,50 U,50 U,50 U,50 U,50 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TB-N139,3,4,2005-09-29,50 U,50 U,50 U,50 U,50 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TB-N140,0.5,2.5,2005-09-29,50 U,50 U,50 U,50 U,50 U,50 U,60,...,60,25,33,10,380,750,5,260,200,240
TB-N140.1,8,10,2005-09-29,50 U,50 U,50 U,50 U,50 U,150,50 U,...,5,25,33,10,5,10,5,10,10,15
TB-N141,13,15,2005-09-24,50 U,50 U,50 U,50 U,50 U,50 U,50 U,...,5,25,33,10,5,10,5,150,10,15
TB-N142,8,10,2005-09-28,50 U,50 U,50 U,50 U,50 U,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TB-N143,8,10,2005-09-28,50 U,50 U,50 U,50 U,53,50 U,50 U,...,5,25,33,10,5,10,5,10,10,15
TB-N144,0.5,2.5,2005-09-28,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT

In [28]:
#make the BNA df
BNA_df_1 = table_df.iloc[0:1]
#pg 101 is 24:45
BNA_df_2 = table_df.iloc[22:44]
BNA_df = pd.concat([BNA_df_1,BNA_df_2])
#transpose it
BNA_df = BNA_df.transpose()
#make the first row our column titles
BNA_df.columns=BNA_df.iloc[0]
#drop the duplicate row
BNA_df = BNA_df.tail(-1)
#drop samples with no detections
BNA_df = BNA_df.dropna(thresh=6)

#drop BNA details for mergining
BNA_df = BNA_df.drop('BNA Extraction Date',axis=1)
BNA_df = BNA_df.drop('BNA Analysis Date',axis=1)
BNA_df = BNA_df.drop('BNA Analytical Method',axis=1)
BNA_df = BNA_df.drop(['Sample Depth (ft bgs)'], axis=1)
BNA_df = BNA_df.drop('BNAs',axis=1) # if needed- keep for explanation

#pull sample id out of index
BNA_df['Sample ID'] = BNA_df.index

#shift column sample ID to first position
first_column = BNA_df.pop('Sample ID')
#insert column using insert(position,column_name,first_column) function
BNA_df.insert(0, 'Sample ID', first_column)

#save detections
BNA_df = BNA_df.drop_duplicates(subset=['Sample ID'], keep="first")

#drop sample ID since its in index
BNA_df = BNA_df.drop(['Sample ID'], axis=1)

BNA_df

Sample ID,Anthracene,Benzo(a)anthracene,Benzo(b)fluoranthene,Benzo(a)pyrene,"Benzo(g,h,i)perylene",Benzo(k)fluoranthene,Carbazole,Chrysene,2-Cloronaphthalene,Di-n-octyl phthalate,Fluoranthene,"Indeno(1,2,3-cd)pyrene",2-Methylnaphthalene,Bis(2-ethylhexyl)phthalate,Phenol,Di-n-butyl phthalate,Phenanthrene,Pyrene
TB-N133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12000,NaN,NaN,NaN,2600,NaN
TB-N134,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TB-N135,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330
TB-N135.1,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N136B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1700,NaN
TB-N137,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TB-N138,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TB-N139,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TB-N140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4700,NaN,NaN,NaN
TB-N140.1,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TB-N141,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330
TB-N142,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TB-N143,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700,1700
TB-N144,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT

In [32]:
#make the leapfrog inputs for BNA
lf_BNA = BNA_df.transpose()
#replace nan w zero
lf_BNA = lf_BNA.replace(np.nan,0)

#turn zeros into nondetections
# # #fix column TB-N133, 136, 140
lf_BNA['TB-N133'] = np.where(lf_BNA['TB-N133']>0, lf_BNA['TB-N133'],'1700 U')
lf_BNA['TB-N136B'] = np.where(lf_BNA['TB-N136B']>0, lf_BNA['TB-N136B'],'1700 U')
lf_BNA['TB-N140'] = np.where(lf_BNA['TB-N140']>0, lf_BNA['TB-N140'],'1700 U')


# #add U to the rest of the columns for non-detects
lf_BNA['TB-N134'] = np.where(lf_BNA['TB-N134']!=1700, lf_BNA['TB-N134'],'1700 U')
lf_BNA['TB-N135'] = np.where(lf_BNA['TB-N135']!=330, lf_BNA['TB-N135'],'330 U')
lf_BNA['TB-N137'] = np.where(lf_BNA['TB-N137']!=1700, lf_BNA['TB-N137'],'1700 U')
lf_BNA['TB-N138'] = np.where(lf_BNA['TB-N138']!=1700, lf_BNA['TB-N138'],'1700 U')
lf_BNA['TB-N139'] = np.where(lf_BNA['TB-N139']!=1700, lf_BNA['TB-N139'],'1700 U')
lf_BNA['TB-N140.1'] = np.where(lf_BNA['TB-N140.1']!=1700, lf_BNA['TB-N140.1'],'1700 U')
lf_BNA['TB-N141'] = np.where(lf_BNA['TB-N141']!=330, lf_BNA['TB-N141'],'330 U')
lf_BNA['TB-N142'] = np.where(lf_BNA['TB-N142']!=1700, lf_BNA['TB-N142'],'1700 U')
lf_BNA['TB-N143'] = np.where(lf_BNA['TB-N143']!=1700, lf_BNA['TB-N143'],'1700 U')

#flip for merging
lf_BNA = lf_BNA.transpose()

#add lf values for BNAs
#added for this dataset
lf_BNA['Anthracene LF'] = np.where(lf_BNA['Anthracene']=='1700 U', 170 ,lf_BNA['Anthracene'])
lf_BNA['Anthracene LF'] = np.where(lf_BNA['Anthracene LF']=='330 U', 33 ,lf_BNA['Anthracene LF'])

lf_BNA['Benzo(a)anthracene LF'] = np.where(lf_BNA['Benzo(a)anthracene']=='1700 U', 170 ,lf_BNA['Benzo(a)anthracene'])
lf_BNA['Benzo(a)anthracene LF'] = np.where(lf_BNA['Benzo(a)anthracene LF']=='330 U', 33 ,lf_BNA['Benzo(a)anthracene LF'])

lf_BNA['Benzo(b)fluoranthene LF'] = np.where(lf_BNA['Benzo(b)fluoranthene']=='1700 U', 170 ,lf_BNA['Benzo(b)fluoranthene'])
lf_BNA['Benzo(b)fluoranthene LF'] = np.where(lf_BNA['Benzo(b)fluoranthene LF']=='330 U', 33 ,lf_BNA['Benzo(b)fluoranthene LF'])

lf_BNA['Benzo(g,h,i)perylene LF'] = np.where(lf_BNA['Benzo(g,h,i)perylene']=='1700 U', 170 ,lf_BNA['Benzo(g,h,i)perylene'])
lf_BNA['Benzo(g,h,i)perylene LF'] = np.where(lf_BNA['Benzo(g,h,i)perylene LF']=='330 U', 33 ,lf_BNA['Benzo(g,h,i)perylene LF'])

lf_BNA['Benzo(a)pyrene LF'] = np.where(lf_BNA['Benzo(a)pyrene']=='1700 U', 170 ,lf_BNA['Benzo(a)pyrene'])
lf_BNA['Benzo(a)pyrene LF'] = np.where(lf_BNA['Benzo(a)pyrene LF']=='330 U', 33 ,lf_BNA['Benzo(a)pyrene LF'])

lf_BNA['Benzo(k)fluoranthene LF'] = np.where(lf_BNA['Benzo(k)fluoranthene']=='1700 U', 170 ,lf_BNA['Benzo(k)fluoranthene'])
lf_BNA['Benzo(k)fluoranthene LF'] = np.where(lf_BNA['Benzo(k)fluoranthene LF']=='330 U', 33 ,lf_BNA['Benzo(k)fluoranthene LF'])

#added for this dataset
lf_BNA['Carbazole LF'] = np.where(lf_BNA['Carbazole']=='1700 U', 170 ,lf_BNA['Carbazole'])
lf_BNA['Carbazole LF'] = np.where(lf_BNA['Carbazole LF']=='330 U', 33 ,lf_BNA['Carbazole LF'])

lf_BNA['Chrysene LF'] = np.where(lf_BNA['Chrysene']=='1700 U', 170 ,lf_BNA['Chrysene'])
lf_BNA['Chrysene LF'] = np.where(lf_BNA['Chrysene LF']=='330 U', 33 ,lf_BNA['Chrysene LF'])

lf_BNA['2-Cloronaphthalene LF'] = np.where(lf_BNA['2-Cloronaphthalene']=='1700 U', 170 ,lf_BNA['2-Cloronaphthalene'])
lf_BNA['2-Cloronaphthalene LF'] = np.where(lf_BNA['2-Cloronaphthalene LF']=='330 U', 33 ,lf_BNA['2-Cloronaphthalene LF'])

#not in this dataset
# lf_BNA['2,4-Dimethylphenol LF'] = np.where(lf_BNA['2,4-Dimethylphenol']=='1700 U', 170 ,lf_BNA['2,4-Dimethylphenol'])
# lf_BNA['2,4-Dimethylphenol LF'] = np.where(lf_BNA['2,4-Dimethylphenol']=='330 U', 33 ,lf_BNA['2,4-Dimethylphenol'])

lf_BNA['Di-n-octyl phthalate LF'] = np.where(lf_BNA['Di-n-octyl phthalate']=='1700 U', 170 ,lf_BNA['Di-n-octyl phthalate'])
lf_BNA['Di-n-octyl phthalate LF'] = np.where(lf_BNA['Di-n-octyl phthalate LF']=='330 U', 33 ,lf_BNA['Di-n-octyl phthalate LF'])

lf_BNA['Fluoranthene LF'] = np.where(lf_BNA['Fluoranthene']=='1700 U', 170 ,lf_BNA['Fluoranthene'])
lf_BNA['Fluoranthene LF'] = np.where(lf_BNA['Fluoranthene LF']=='330 U', 33 ,lf_BNA['Fluoranthene LF'])

lf_BNA['Indeno(1,2,3-cd)pyrene LF'] = np.where(lf_BNA['Indeno(1,2,3-cd)pyrene']=='1700 U', 170 ,lf_BNA['Indeno(1,2,3-cd)pyrene'])
lf_BNA['Indeno(1,2,3-cd)pyrene LF'] = np.where(lf_BNA['Indeno(1,2,3-cd)pyrene LF']=='330 U', 33 ,lf_BNA['Indeno(1,2,3-cd)pyrene LF'])

lf_BNA['2-Methylnaphthalene LF'] = np.where(lf_BNA['2-Methylnaphthalene']=='1700 U', 170 ,lf_BNA['2-Methylnaphthalene'])
lf_BNA['2-Methylnaphthalene LF'] = np.where(lf_BNA['2-Methylnaphthalene LF']=='330 U', 33 ,lf_BNA['2-Methylnaphthalene LF'])

lf_BNA['Bis(2-ethylhexyl)phthalate LF'] = np.where(lf_BNA['Bis(2-ethylhexyl)phthalate']=='1700 U', 170 ,lf_BNA['Bis(2-ethylhexyl)phthalate'])
lf_BNA['Bis(2-ethylhexyl)phthalate LF'] = np.where(lf_BNA['Bis(2-ethylhexyl)phthalate LF']=='330 U', 33 ,lf_BNA['Bis(2-ethylhexyl)phthalate LF'])

lf_BNA['Phenol LF'] = np.where(lf_BNA['Phenol']=='1700 U', 170 ,lf_BNA['Phenol'])
lf_BNA['Phenol LF'] = np.where(lf_BNA['Phenol LF']=='330 U', 33 ,lf_BNA['Phenol LF'])

lf_BNA['Di-n-butyl phthalate LF'] = np.where(lf_BNA['Di-n-butyl phthalate']=='1700 U', 170 ,lf_BNA['Di-n-butyl phthalate'])
lf_BNA['Di-n-butyl phthalate LF'] = np.where(lf_BNA['Di-n-butyl phthalate LF']=='330 U', 33 ,lf_BNA['Di-n-butyl phthalate LF'])

lf_BNA['Phenanthrene LF'] = np.where(lf_BNA['Phenanthrene']=='1700 U', 170 ,lf_BNA['Phenanthrene'])
lf_BNA['Phenanthrene LF'] = np.where(lf_BNA['Phenanthrene LF']=='330 U', 33 ,lf_BNA['Phenanthrene LF'])

lf_BNA['Pyrene LF'] = np.where(lf_BNA['Pyrene']=='1700 U', 170 ,lf_BNA['Pyrene'])
lf_BNA['Pyrene LF'] = np.where(lf_BNA['Pyrene LF']=='330 U', 33 ,lf_BNA['Pyrene LF'])

lf_BNA

Sample ID,Anthracene,Benzo(a)anthracene,Benzo(b)fluoranthene,Benzo(a)pyrene,"Benzo(g,h,i)perylene",Benzo(k)fluoranthene,Carbazole,Chrysene,2-Cloronaphthalene,Di-n-octyl phthalate,...,2-Cloronaphthalene LF,Di-n-octyl phthalate LF,Fluoranthene LF,"Indeno(1,2,3-cd)pyrene LF",2-Methylnaphthalene LF,Bis(2-ethylhexyl)phthalate LF,Phenol LF,Di-n-butyl phthalate LF,Phenanthrene LF,Pyrene LF
TB-N133,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,12000,170,170,170,2600,170
TB-N134,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TB-N135,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,...,33,33,33,33,33,33,33,33,33,33
TB-N135.1,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N136B,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,1700,170
TB-N137,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TB-N138,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TB-N139,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TB-N140,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,4700,170,170,170
TB-N140.1,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TB-N141,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,330 U,...,33,33,33,33,33,33,33,33,33,33
TB-N142,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TB-N143,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,1700 U,...,170,170,170,170,170,170,170,170,170,170
TB-N144,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT

In [33]:
#make the metals df
metals_df_1 = table_df.iloc[0:1]
metals_df_2 = table_df.iloc[44:60]
metals_df = pd.concat([metals_df_1,metals_df_2])
# #transpose it
metals_df = metals_df.transpose()
# #make the first row our column titles
metals_df.columns=metals_df.iloc[0]
# #drop the duplicate row
metals_df = metals_df.tail(-1)
#drop metals details for merging
metals_df = metals_df.drop('Metals Analysis Date',axis=1) 
metals_df = metals_df.drop('Analytical Method',axis=1)
metals_df = metals_df.drop('Metals',axis=1) #- keep for explanation
# #drop samples with no detections
metals_df = metals_df.dropna(thresh=2)

#pull sample id out of index
metals_df['Sample ID'] = metals_df.index
#shift column sample ID to first position
first_column = metals_df.pop('Sample ID')
#insert column using insert(position,column_name,first_column) function
metals_df.insert(0, 'Sample ID', first_column)

#drop samples with no detections
metals_df = metals_df.drop_duplicates(subset=['Sample ID'], keep="first")

#drop informational columns for merging
metals_df = metals_df.drop(['Sample ID'], axis=1)
metals_df = metals_df.drop(['Sample Depth (ft bgs)'], axis=1)

############################################
metals_df

Sample ID,Arsenic,Barium,Cadmium,Chromium,Chromium IV,"Lead, total (calculated)","Lead, fine fraction","Lead, coarse fraction",Manganese,Mercury,Nickel,Vanadium,Zinc
TB-N133,590,390000,NaN,11000,NaN,31300,11000,35000,3200000,NaN,1700,4700,2600
TB-N134,6200,170000,1500,36000,NaN,343000,212000,377000,940000,280,42000,12000,99000
TB-N135,6100,86000,420,24000,NaN,15000,23600,13400,760000,NaN,25000,14000,60000
TB-N135.1,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N136B,6500,130000,8600,110000,NaN,112000,218000,90800,1700000,280,5100,17000,170000
TB-N137,10000,120000,1900,82000,NaN,854000,414000,981000,7300000,800,74000,16000,420000
TB-N138,300,310000,NaN,4000,NaN,3200,6070,3080,1900000,NaN,3200,2500,NaN
TB-N139,900,380000,NaN,15000,NaN,5310,14500,4910,3600000,NaN,4300,7300,8200
TB-N140,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N140.1,2000,43000,630,35000,NaN,30300,81200,19900,950000,NaN,14000,6300,29000
TB-N141,5300,70000,1100,28000,NaN,53600,81900,37900,650000,NaN,20000,13000,69000
TB-N142,3900,190000,1000,24000,NaN,20900,64500,15900,530000,NaN,28000,16000,63000
TB-N143,18000,550000,2200,54000,NaN,50200,100000,22200,810000,NaN,73000,16000,280000
TB-N144,3600,150000,1100,750000,NaN,191000,299000,189000,12000000,360,21000,220000,1300000

In [35]:
#make the leapfrog inputs for metals
lf_metals = metals_df
#replace nan w zero
lf_metals = lf_metals.replace(np.nan,0)

#isolate the results
lf_metals = lf_metals.iloc[0:]

#fix mercury non detect
lf_metals['Mercury'] = np.where(lf_metals['Mercury']==0, f'50' + ' U' , lf_metals['Mercury'])
#add mercury LF column
lf_metals['Mercury LF'] = np.where(lf_metals['Mercury']=='50 U', 5 , lf_metals['Mercury'])
# fix Chromium IV nondetect
lf_metals['Chromium IV'] = np.where(lf_metals['Chromium IV']==0, f'500' + ' U' , lf_metals['Chromium IV'])
#add chromium LF column
lf_metals['Chromium IV LF'] = np.where(lf_metals['Chromium IV']=='500 U', 50 , lf_metals['Chromium IV'])
#fix cadmium non detect
lf_metals['Cadmium'] = np.where(lf_metals['Cadmium']==0, f'50' + ' U' , lf_metals['Cadmium'])
#add cadmium LF column
lf_metals['Cadmium LF'] = np.where(lf_metals['Cadmium']=='50 U', 5 , lf_metals['Cadmium'])

lf_metals

Sample ID,Arsenic,Barium,Cadmium,Chromium,Chromium IV,"Lead, total (calculated)","Lead, fine fraction","Lead, coarse fraction",Manganese,Mercury,Nickel,Vanadium,Zinc,Mercury LF,Chromium IV LF,Cadmium LF
TB-N133,590,390000,50 U,11000,500 U,31300,11000,35000,3200000,50 U,1700,4700,2600,5,50,5
TB-N134,6200,170000,1500,36000,500 U,343000,212000,377000,940000,280,42000,12000,99000,280,50,1500
TB-N135,6100,86000,420,24000,500 U,15000,23600,13400,760000,50 U,25000,14000,60000,5,50,420
TB-N135.1,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N136B,6500,130000,8600,110000,500 U,112000,218000,90800,1700000,280,5100,17000,170000,280,50,8600
TB-N137,10000,120000,1900,82000,500 U,854000,414000,981000,7300000,800,74000,16000,420000,800,50,1900
TB-N138,300,310000,50 U,4000,500 U,3200,6070,3080,1900000,50 U,3200,2500,0,5,50,5
TB-N139,900,380000,50 U,15000,500 U,5310,14500,4910,3600000,50 U,4300,7300,8200,5,50,5
TB-N140,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N140.1,2000,43000,630,35000,500 U,30300,81200,19900,950000,50 U,14000,6300,29000,5,50,630
TB-N141,5300,70000,1100,28000,500 U,53600,81900,37900,650000,50 U,20000,13000,69000,5,50,1100
TB-N142,3900,190000,1000,24000,500 U,20900,64500,15900,530000,50 U,28000,16000,63000,5,50,1000
TB-N143,18000,550000,2200,54000,500 U,50200,100000,22200,810000,50 U,73000,16000,280000,5,50,2200
TB-N144,3600,150000,1100,750000,500 U,191000,299000,189000,12000000,360,21000,220000,1300000,360,50,1100

In [36]:
#make the PCBs df
PCB_df_1 = table_df.iloc[0:1]
PCB_df_2 = table_df.iloc[60:65]
PCB_df = pd.concat([PCB_df_1,PCB_df_2])
# #transpose it
PCB_df = PCB_df.transpose()
#make the first row our column titles
PCB_df.columns=PCB_df.iloc[0]
#drop the duplicate row
PCB_df = PCB_df.tail(-1)
#drop extra info
PCB_df = PCB_df.drop('PCB Extraction Date',axis=1)
PCB_df = PCB_df.drop('PCB Analysis Date',axis=1)
PCB_df = PCB_df.drop('PCB Analytical Method',axis=1)
PCB_df = PCB_df.drop('PCBs',axis=1)
#drop samples with no detections
PCB_df = PCB_df.dropna(thresh=2)
#indicate the nondetects
PCB_df = PCB_df.replace(np.nan,'330 U')

#pull sample id out of index
PCB_df['Sample ID'] = PCB_df.index
#shift column sample ID to first position
first_column = PCB_df.pop('Sample ID')
#insert column using insert(position,column_name,first_column) function
PCB_df.insert(0, 'Sample ID', first_column)

#drop duplicate rows
PCB_df = PCB_df.drop_duplicates(subset=['Sample ID'], keep="first")

#drop extra info
PCB_df = PCB_df.drop(['Sample Depth (ft bgs)'], axis=1)
PCB_df = PCB_df.drop(['Sample ID'], axis=1)

PCB_df

Sample ID Aroclors
TB-N133         NT
TB-N134         NT
TB-N135        330
TB-N135.1      330
TB-N136B       330
TB-N137        330
TB-N138         NT
TB-N139         NT
TB-N140        330
TB-N140.1      330
TB-N141        330
TB-N142        330
TB-N143         NT
TB-N144         NT

In [37]:
#make the leapfrog inputs for PCBs
lf_PCB = PCB_df

#modify existing columns for leapfrog
#only general Aroclors for this data
lf_PCB['Aroclors'] = np.where(lf_PCB['Aroclors'] == 330 , '330 U' ,lf_PCB['Aroclors'])
#lf_PCB['Aroclor-1254'] = np.where(lf_PCB['Aroclor-1254'] == 330 , '330 U' ,lf_PCB['Aroclor-1254'])
#lf_PCB['Aroclor-1260'] = np.where(lf_PCB['Aroclor-1260'] == 330, '330 U' ,lf_PCB['Aroclor-1260'])

#add leapfrog input for PCBs
lf_PCB['Aroclors LF'] = np.where(lf_PCB['Aroclors'] == '330 U' , 3.3 ,lf_PCB['Aroclors'])
# lf_PCB['Aroclor-1254 LF'] = np.where(lf_PCB['Aroclor-1254'] == '330 U', 3.3 ,lf_PCB['Aroclor-1254'])
# lf_PCB['Aroclor-1260 LF'] = np.where(lf_PCB['Aroclor-1260'] == '330 U', 3.3 ,lf_PCB['Aroclor-1260'])

lf_PCB

Sample ID Aroclors Aroclors LF
TB-N133         NT          NT
TB-N134         NT          NT
TB-N135      330 U         3.3
TB-N135.1    330 U         3.3
TB-N136B     330 U         3.3
TB-N137      330 U         3.3
TB-N138         NT          NT
TB-N139         NT          NT
TB-N140      330 U         3.3
TB-N140.1    330 U         3.3
TB-N141      330 U         3.3
TB-N142      330 U         3.3
TB-N143         NT          NT
TB-N144         NT          NT

In [38]:
#merge tables
combined_lf= pd.merge(lf_BNA,lf_metals, left_index = True, right_index = True)
combined_lf= pd.merge(combined_lf,lf_PCB, left_index = True, right_index = True)
combined_lf= pd.merge(combined_lf,lf_voc, left_index = True, right_index = True)

#shift depths and date to front of df 
first_column = combined_lf.pop('Start_Depth')
second_column = combined_lf.pop('End_Depth')
third_column = combined_lf.pop('Sample_Date')

#sort columns alphabetically
combined_lf = combined_lf.sort_index(axis = 1, ascending = True)
  
#insert column using insert(position,column_name,first_column) function
combined_lf.insert(0, 'Start_Depth', first_column)
combined_lf.insert(1, 'End_Depth', second_column)
combined_lf.insert(2, 'Sample_Date', third_column)

#setindex name
combined_lf.index.name='Sample_ID'

combined_lf

Sample ID,Start_Depth,End_Depth,Sample_Date,"1,1-Dichloroethane","1,1-Dichloroethane LF","1,2,4-Trimethylbenzene","1,2,4-Trimethylbenzene LF","1,3,5-Trimethylbenzene","1,3,5-Trimethylbenzene LF",2-Cloronaphthalene,...,Xylenes LF,Zinc,"cis-1,2-Dichloroethene","cis-1,2-Dichloroethene LF",n-Butylbenzene,n-Butylbenzene LF,n-Propylbenzene,n-Propylbenzene LF,sec-Butylbenzene,sec-Butylbenzene LF
Sample_ID,,,,,,,,,,,,,,,,,,,,,
TB-N133,5.5,6,2005-09-27,50 U,5,3500,3500,1100,1100,1700 U,...,2200,2600,50 U,5,560,560,360,360,280,280
TB-N134,5.5,7.5,2005-09-27,50 U,5,100 U,10,100 U,10,1700 U,...,15,99000,50 U,5,50 U,5,100 U,10,50 U,5
TB-N135,5.5,7.5,2005-09-24,50 U,5,100 U,10,100 U,10,330 U,...,15,60000,50 U,5,50 U,5,100 U,10,50 U,5
TB-N135.1,10.5,12.5,2005-09-24,NT,NT,NT,NT,NT,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
TB-N136B,10.5,12.5,2005-09-26,50 U,5,420,420,230,230,1700 U,...,770,170000,50 U,5,54,54,100 U,10,50 U,5
TB-N137,10.5,12.5,2005-09-26,50 U,5,200,200,100 U,10,1700 U,...,180,420000,50 U,5,50 U,5,100 U,10,50 U,5
TB-N138,2.5,5.0,2005-09-27,50 U,5,100 U,10,100 U,10,1700 U,...,15,0,50 U,5,50 U,5,100 U,10,50 U,5
TB-N139,3,4,2005-09-29,50 U,5,100 U,10,100 U,10,1700 U,...,15,8200,50 U,5,50 U,5,100 U,10,50 U,5
TB-N140,0.5,2.5,2005-09-29,50 U,5,260,260,200,200,1700 U,...,240,NT,50 U,5,50 U,5,100 U,10,50 U,5
TB-N140.1,8,10,2005-09-29,50 U,5,100 U,10,100 U,10,1700 U,...,15,29000,150,150,50 U,5,100 U,10,50 U,5
TB-N141,13,15,2005-09-24,50 U,5,150,150,100 U,10,330 U,...,15,69000,50 U,5,50 U,5,100 U,10,50 U,5
TB-N142,8,10,2005-09-28,50 U,5,100 U,10,100 U,10,1700 U,...,15,63000,50 U,5,50 U,5,100 U,10,50 U,5
TB-N143,8,10,2005-09-28,53,53,100 U,10,100 U,10,1700 U,...,15,280000,50 U,5,50 U,5,100 U,10,50 U,5
TB-N144,0.5,2.5,2005-09-28,NT,NT,NT,NT,NT,NT,NT,...,NT,1300000,NT,NT,NT,NT,NT,NT,NT,NT

In [39]:
combined_lf.to_csv('LeapFrog Exports/Pg97.csv')